<?php

namespace Database\Seeders;

use App\Models\OurTeam;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class OurTeamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ourTeams = array(
            array(
                'id' => 1,
                'name' => 'Jannat Alam Sneha',
                'name_bn' => 'জান্নাত আলম স্নেহা',
                'email' => 'alfahiminternational944@gmail.com',
                'phone' => '+8801349656021',
                'phone_bn' => '+৮৮০১৩৪৯৬৫৬০২১',
                'designation' => 'Manager',
                'designation_bn' => 'ম্যানেজার',
                'facebook' => 'https://www.facebook.com/share/196jqwbpyM/',
                'twitter' => 'https://twitter.com/',
                'instagram' => 'https://www.instagram.com/',
                'youtube' => 'https://www.youtube.com/',
                'experience' => '8 years',
                'experience_bn' => '৮ বছর',
                'biography' => '<p>Jannat Alam Sneha serves as the Manager at AL FAHIM INTERNATIONAL. With over 8 years of proven leadership in foreign manpower recruitment and operational management, she supervises daily agency workflows, recruitment teams, and candidate placement procedures.</p><p>She is committed to maintaining strict compliance with government regulatory bodies, BMET protocols, and foreign employer standards, ensuring transparent, ethical, and hassle-free overseas employment for thousands of candidates.</p>',
                'biography_bn' => '<p>জান্নাত আলম স্নেহা আল ফাহিম ইন্টারন্যাশনালের ম্যানেজার হিসেবে দায়িত্ব পালন করছেন। জনশক্তি নিয়োগ এবং পরিচালনায় ৮ বছরেরও বেশি অভিজ্ঞতার সাথে, তিনি সংস্থার দৈনন্দিন কার্যক্রম এবং নিয়োগ পদ্ধতি তত্ত্বাবধান করেন।</p><p>তিনি সরকারি বিধিবিধান এবং বিদেশী নিয়োগকর্তার মান বজায় রাখতে প্রতিশ্রুতিবদ্ধ, যাতে প্রার্থীদের জন্য স্বচ্ছ এবং ঝামেলামুক্ত বিদেশী কর্মসংস্থান নিশ্চিত করা যায়।</p>',
                'image' => 'upload/our_team/jannat_alam_sneha.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ),
            array(
                'id' => 2,
                'name' => 'Sohani',
                'name_bn' => 'সোহানী',
                'email' => 'alfahiminternational944@gmail.com',
                'phone' => '+8801349656026',
                'phone_bn' => '+৮৮০১৩৪৯৬৫৬০২৬',
                'designation' => 'Ass. Marketing Manager',
                'designation_bn' => 'সহকারী মার্কেটিং ম্যানেজার',
                'facebook' => 'https://www.facebook.com/share/196jqwbpyM/',
                'twitter' => 'https://twitter.com/',
                'instagram' => 'https://www.instagram.com/',
                'youtube' => 'https://www.youtube.com/',
                'experience' => '6 years',
                'experience_bn' => '৬ বছর',
                'biography' => '<p>Sohani is the Assistant Marketing Manager at AL FAHIM INTERNATIONAL. She plays a pivotal role in formulating and executing strategic marketing campaigns across digital and regional platforms to connect skilled job seekers with premium foreign employers.</p><p>Her expertise spans brand development, campaign analytics, employer outreach, and organizing large-scale overseas recruitment drives across Bangladesh.</p>',
                'biography_bn' => '<p>সোহানী আল ফাহিম ইন্টারন্যাশনালের সহকারী মার্কেটিং ম্যানেজার। তিনি দক্ষ চাকরি প্রার্থীদের বিদেশী নিয়োগকর্তাদের সাথে যুক্ত করতে কৌশলগত বিপণন প্রচারাভিযান প্রণয়ন এবং পরিচালনায় গুরুত্বপূর্ণ ভূমিকা পালন করেন।</p><p>তার দক্ষতা ব্র্যান্ড উন্নয়ন, প্রচারাভিযান বিশ্লেষণ এবং বাংলাদেশ জুড়ে বিদেশী নিয়োগ প্রক্রিয়ায় বিস্তৃত।</p>',
                'image' => null,
                'created_at' => now(),
                'updated_at' => now()
            ),
            array(
                'id' => 3,
                'name' => 'Rafsan Jani',
                'name_bn' => 'রাফসান জানি',
                'email' => 'alfahiminternational944@gmail.com',
                'phone' => '+8801349656028',
                'phone_bn' => '+৮৮০১৩৪৯৬৫৬০২৮',
                'designation' => 'Marketing Officer',
                'designation_bn' => 'মার্কেটিং অফিসার',
                'facebook' => 'https://www.facebook.com/share/196jqwbpyM/',
                'twitter' => 'https://twitter.com/',
                'instagram' => 'https://www.instagram.com/',
                'youtube' => 'https://www.youtube.com/',
                'experience' => '4 years',
                'experience_bn' => '৪ বছর',
                'biography' => '<p>Rafsan Jani works as a dedicated Marketing Officer at AL FAHIM INTERNATIONAL. He specializes in candidate engagement, technical trade test coordination, and professional skill assessment for international recruitment.</p><p>He works closely with job seekers targeting construction, heavy industry, and hospitality vacancies in Saudi Arabia, the UAE, and Europe, guiding them through every step from registration to departure.</p>',
                'biography_bn' => '<p>রাফসান জানি আল ফাহিম ইন্টারন্যাশনালের একজন নিবেদিত মার্কেটিং অফিসার। তিনি আন্তর্জাতিক নিয়োগের জন্য প্রার্থী সম্পৃক্ততা এবং দক্ষতা মূল্যায়নে বিশেষজ্ঞ।</p><p>তিনি সৌদি আরব, সংযুক্ত আরব আমিরাত এবং ইউরোপে চাকরিরত প্রার্থীদের সাথে ঘনিষ্ঠভাবে কাজ করেন, নিবন্ধন থেকে প্রস্থান পর্যন্ত প্রতিটি পদক্ষেপে তাদের গাইড করেন।</p>',
                'image' => 'upload/our_team/rafsan_jani.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ),
            array(
                'id' => 4,
                'name' => 'Nadim',
                'name_bn' => 'নাদিম',
                'email' => 'alfahiminternational944@gmail.com',
                'phone' => '+8801349656022',
                'phone_bn' => '+৮৮০১৩৪৯৬৫৬০২২',
                'designation' => 'Marketing Officer',
                'designation_bn' => 'মার্কেটিং অফিসার',
                'facebook' => 'https://www.facebook.com/share/196jqwbpyM/',
                'twitter' => 'https://twitter.com/',
                'instagram' => 'https://www.instagram.com/',
                'youtube' => 'https://www.youtube.com/',
                'experience' => '3 years',
                'experience_bn' => '৩ বছর',
                'biography' => '<p>Nadim is a proactive Marketing Officer known for his comprehensive candidate counseling and client relationship management at AL FAHIM INTERNATIONAL.</p><p>He assists applicants with job selection, contract term clarification, salary transparency, and document preparation, ensuring candidates are fully informed and well-prepared for their overseas careers.</p>',
                'biography_bn' => '<p>নাদিম আল ফাহিম ইন্টারন্যাশনালের একজন সক্রিয় মার্কেটিং অফিসার, যিনি প্রার্থীদের ব্যাপক পরামর্শ এবং ক্লায়েন্ট সম্পর্ক পরিচালনার জন্য পরিচিত।</p><p>তিনি আবেদনকারীদের চাকরি নির্বাচন এবং নথিপত্র প্রস্তুতিতে সহায়তা করেন, যাতে প্রার্থীরা তাদের বিদেশী ক্যারিয়ারের জন্য সম্পূর্ণ প্রস্তুত থাকেন।</p>',
                'image' => 'upload/our_team/nadim.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ),
            array(
                'id' => 5,
                'name' => 'Mizanur Rahman',
                'name_bn' => 'মিজানুর রহমান',
                'email' => 'alfahiminternational944@gmail.com',
                'phone' => '+8801326748243',
                'phone_bn' => '+৮৮০১৩২৬৭৪৮২৪৩',
                'designation' => 'Marketing Officer',
                'designation_bn' => 'মার্কেটিং অফিসার',
                'facebook' => 'https://www.facebook.com/share/196jqwbpyM/',
                'twitter' => 'https://twitter.com/',
                'instagram' => 'https://www.instagram.com/',
                'youtube' => 'https://www.youtube.com/',
                'experience' => '5 years',
                'experience_bn' => '৫ বছর',
                'biography' => '<p>Mizanur Rahman brings over 5 years of rich experience as a Marketing Officer at AL FAHIM INTERNATIONAL. His primary focus is on regional talent sourcing, employer circular dissemination, and field outreach programs.</p><p>He has successfully guided hundreds of candidates into overseas placements in Malaysia, the Middle East, and Eastern European countries through ethical recruitment practices.</p>',
                'biography_bn' => '<p>মিজানুর রহমান আল ফাহিম ইন্টারন্যাশনালে মার্কেটিং অফিসার হিসেবে ৫ বছরেরও বেশি অভিজ্ঞতা নিয়ে কাজ করছেন। তার মূল কাজ আঞ্চলিক মেধা সংগ্রহ এবং প্রচার।</p><p>তিনি নৈতিক নিয়োগের মাধ্যমে শত শত প্রার্থীকে মালয়েশিয়া, মধ্যপ্রাচ্য এবং ইউরোপে সফলভাবে নিয়োগ পেতে সহায়তা করেছেন।</p>',
                'image' => 'upload/our_team/mizanur_rahman.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ),
            array(
                'id' => 6,
                'name' => 'Suchona',
                'name_bn' => 'সূচনা',
                'email' => 'alfahiminternational944@gmail.com',
                'phone' => '+8801349656031',
                'phone_bn' => '+৮৮০১৩৪৯৬৫৬০৩১',
                'designation' => 'Receptionist',
                'designation_bn' => 'রিসিপশনিস্ট',
                'facebook' => 'https://www.facebook.com/share/196jqwbpyM/',
                'twitter' => 'https://twitter.com/',
                'instagram' => 'https://www.instagram.com/',
                'youtube' => 'https://www.youtube.com/',
                'experience' => '3 years',
                'experience_bn' => '৩ বছর',
                'biography' => '<p>Suchona is the welcoming front-desk Receptionist at AL FAHIM INTERNATIONAL. As the first point of contact for visitors and prospective candidates, she ensures warm hospitality, manages appointment schedules, and answers general queries.</p><p>She also handles incoming phone communications, directs candidates to the appropriate counseling desks, and maintains the front-office guest log with utmost professionalism.</p>',
                'biography_bn' => '<p>সূচনা আল ফাহিম ইন্টারন্যাশনালের ফ্রন্ট-ডেস্ক রিসিপশনিস্ট। দর্শনার্থী এবং প্রার্থীদের প্রথম যোগাযোগের মাধ্যম হিসেবে, তিনি আন্তরিক আতিথেয়তা এবং সময়সূচী পরিচালনা করেন।</p><p>তিনি ইনকামিং ফোন যোগাযোগ পরিচালনা করেন এবং প্রার্থীদের সঠিক কাউন্সেলিং ডেস্কে নির্দেশ করেন।</p>',
                'image' => 'upload/our_team/suchona.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ),
            array(
                'id' => 7,
                'name' => 'Suyab Khan',
                'name_bn' => 'সুয়াব খান',
                'email' => 'alfahiminternational944@gmail.com',
                'phone' => '+8801349656020',
                'phone_bn' => '+৮৮০১৩৪৯৬৫৬০২০',
                'designation' => 'IT Officer',
                'designation_bn' => 'আইটি অফিসার',
                'facebook' => 'https://www.facebook.com/share/196jqwbpyM/',
                'twitter' => 'https://twitter.com/',
                'instagram' => 'https://www.instagram.com/',
                'youtube' => 'https://www.youtube.com/',
                'experience' => '4 years',
                'experience_bn' => '৪ বছর',
                'biography' => '<p>Suyab Khan is an IT Officer at AL FAHIM INTERNATIONAL, responsible for maintaining office technology infrastructure, candidate database management, and network security.</p><p>He oversees automated application tracking systems, digital biometric archiving, and system reliability to support uninterrupted agency operations and fast-track digital processing.</p>',
                'biography_bn' => '<p>সুয়াব খান আল ফাহিম ইন্টারন্যাশনালের একজন আইটি অফিসার, যিনি প্রযুক্তিগত অবকাঠামো, ডাটাবেস পরিচালনা এবং নেটওয়ার্ক সুরক্ষার দায়িত্বে আছেন।</p><p>তিনি স্বয়ংক্রিয় অ্যাপ্লিকেশন ট্র্যাকিং এবং ডিজিটাল বায়োমেট্রিক সংরক্ষণ তদারকি করেন।</p>',
                'image' => 'upload/our_team/suyab_khan.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ),
            array(
                'id' => 8,
                'name' => 'Ornob Ahmed',
                'name_bn' => 'অর্ণব আহমেদ',
                'email' => 'alfahiminternational944@gmail.com',
                'phone' => '+8801340395635',
                'phone_bn' => '+৮৮০১৩৪০৩৯৫৬৩৫',
                'designation' => 'IT Officer',
                'designation_bn' => 'আইটি অফিসার',
                'facebook' => 'https://www.facebook.com/share/196jqwbpyM/',
                'twitter' => 'https://twitter.com/',
                'instagram' => 'https://www.instagram.com/',
                'youtube' => 'https://www.youtube.com/',
                'experience' => '4 years',
                'experience_bn' => '৪ বছর',
                'biography' => '<p>Ornob Ahmed serves as an IT Officer at AL FAHIM INTERNATIONAL, handling website updates, digital portals, hardware maintenance, and data backup solutions.</p><p>He ensures that online candidate registrations, visa status tracking tools, and client communications run smoothly and securely around the clock.</p>',
                'biography_bn' => '<p>অর্ণব আহমেদ আল ফাহিম ইন্টারন্যাশনালের একজন আইটি অফিসার, যিনি ওয়েবসাইট আপডেট, ডিজিটাল পোর্টাল এবং হার্ডওয়্যার রক্ষণাবেক্ষণের কাজ করেন।</p><p>তিনি নিশ্চিত করেন যে অনলাইন নিবন্ধন এবং ভিসা স্ট্যাটাস ট্র্যাকিং সরঞ্জামগুলো সুচারুভাবে কাজ করে।</p>',
                'image' => 'upload/our_team/ornob_ahmed.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ),
            array(
                'id' => 9,
                'name' => 'Hasnain Ahmed',
                'name_bn' => 'হাসনাইন আহমেদ',
                'email' => 'alfahiminternational944@gmail.com',
                'phone' => '+8801354935708',
                'phone_bn' => '+৮৮০১৩৫৪৯৩৫৭০৮',
                'designation' => 'Marketing Officer',
                'designation_bn' => 'মার্কেটিং অফিসার',
                'facebook' => 'https://www.facebook.com/share/196jqwbpyM/',
                'twitter' => 'https://twitter.com/',
                'instagram' => 'https://www.instagram.com/',
                'youtube' => 'https://www.youtube.com/',
                'experience' => '3 years',
                'experience_bn' => '৩ বছর',
                'biography' => '<p>Hasnain Ahmed is an energetic Marketing Officer at AL FAHIM INTERNATIONAL, specializing in public relations, field outreach, and overseas job promotion.</p><p>He actively assists job seekers in understanding medical clearance procedures, embassy documentation, and visa verification stages, providing trustworthy support at every phase.</p>',
                'biography_bn' => '<p>হাসনাইন আহমেদ আল ফাহিম ইন্টারন্যাশনালের একজন উদ্যমী মার্কেটিং অফিসার, যিনি জনসংযোগ এবং বিদেশী চাকরি প্রচারে বিশেষজ্ঞ।</p><p>তিনি মেডিকেল ক্লিয়ারেন্স, দূতাবাস ডকুমেন্টেশন এবং ভিসা যাচাইকরণ সম্পর্কে চাকরি প্রার্থীদের সহায়তা করেন।</p>',
                'image' => 'upload/our_team/hasnain_ahmed.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ),
            array(
                'id' => 10,
                'name' => 'Nayon Tara',
                'name_bn' => 'নয়ন তারা',
                'email' => 'alfahiminternational944@gmail.com',
                'phone' => '+8801353892206',
                'phone_bn' => '+৮৮০১৩৫৩৮৯২২০৬',
                'designation' => 'Marketing Officer',
                'designation_bn' => 'মার্কেটিং অফিসার',
                'facebook' => 'https://www.facebook.com/share/196jqwbpyM/',
                'twitter' => 'https://twitter.com/',
                'instagram' => 'https://www.instagram.com/',
                'youtube' => 'https://www.youtube.com/',
                'experience' => '3 years',
                'experience_bn' => '৩ বছর',
                'biography' => '<p>Nayon Tara is a Marketing Officer at AL FAHIM INTERNATIONAL focused on candidate guidance, hospitality sector recruitment, and customer service.</p><p>She provides personalized counseling to prospective candidates, clarifying job responsibilities, accommodation details, and workplace benefits for foreign placements.</p>',
                'biography_bn' => '<p>নয়ন তারা আল ফাহিম ইন্টারন্যাশনালের একজন মার্কেটিং অফিসার, যিনি প্রার্থীর দিকনির্দেশনা এবং আতিথেয়তা খাতে নিয়োগে নিবদ্ধ।</p><p>তিনি প্রার্থীদের ব্যক্তিগত কাউন্সেলিং প্রদান করে কাজের দায়িত্ব ও সুবিধা সম্পর্কে পরিষ্কার ধারণা দেন।</p>',
                'image' => null,
                'created_at' => now(),
                'updated_at' => now()
            ),
            array(
                'id' => 11,
                'name' => 'Shihab',
                'name_bn' => 'শিহাব',
                'email' => 'alfahiminternational944@gmail.com',
                'phone' => '+8801882699747',
                'phone_bn' => '+৮৮০১৮৮২৬৯৯৭৪৭',
                'designation' => 'Marketing Officer',
                'designation_bn' => 'মার্কেটিং অফিসার',
                'facebook' => 'https://www.facebook.com/share/196jqwbpyM/',
                'twitter' => 'https://twitter.com/',
                'instagram' => 'https://www.instagram.com/',
                'youtube' => 'https://www.youtube.com/',
                'experience' => '3 years',
                'experience_bn' => '৩ বছর',
                'biography' => '<p>Shihab serves as a Marketing Officer at AL FAHIM INTERNATIONAL, specializing in candidate recruitment for technical trades, driving, logistics, and industrial sectors.</p><p>He works diligently to match candidate credentials with verified foreign demand orders, ensuring high selection rates during employer interviews.</p>',
                'biography_bn' => '<p>শিহাব আল ফাহিম ইন্টারন্যাশনালের মার্কেটিং অফিসার, যিনি কারিগরি ট্রেড এবং ড্রাইভিং সেক্টরে প্রার্থী নিয়োগে বিশেষজ্ঞ।</p><p>তিনি বিদেশী চাহিদার সাথে প্রার্থীর যোগ্যতা মেলানোর জন্য নিবিড়ভাবে কাজ করেন।</p>',
                'image' => 'upload/our_team/shihab.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ),
            array(
                'id' => 12,
                'name' => 'Sajib',
                'name_bn' => 'সজিব',
                'email' => 'alfahiminternational944@gmail.com',
                'phone' => '+8801351340814',
                'phone_bn' => '+৮৮০১৩৫১৩৪০৮১৪',
                'designation' => 'Marketing Officer',
                'designation_bn' => 'মার্কেটিং অফিসার',
                'facebook' => 'https://www.facebook.com/share/196jqwbpyM/',
                'twitter' => 'https://twitter.com/',
                'instagram' => 'https://www.instagram.com/',
                'youtube' => 'https://www.youtube.com/',
                'experience' => '3 years',
                'experience_bn' => '৩ বছর',
                'biography' => '<p>Sajib is a Marketing Officer at AL FAHIM INTERNATIONAL, managing direct applicant inquiries, hotline support, and candidate onboarding.</p><p>His prompt communication and clear explanations help candidates navigate passport submissions, GAMCA medical tests, and pre-departure briefings with confidence.</p>',
                'biography_bn' => '<p>সজিব আল ফাহিম ইন্টারন্যাশনালের একজন মার্কেটিং অফিসার, যিনি সরাসরি আবেদনকারীদের জিজ্ঞাসা এবং অনবোর্ডিং পরিচালনা করেন।</p><p>তার দ্রুত যোগাযোগ প্রার্থীদের পাসপোর্ট জমা এবং মেডিকেল পরীক্ষায় সহায়তা করে।</p>',
                'image' => 'upload/our_team/sajib.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ),
            array(
                'id' => 13,
                'name' => 'Ashik',
                'name_bn' => 'আশিক',
                'email' => 'alfahiminternational944@gmail.com',
                'phone' => '+8801349656027',
                'phone_bn' => '+৮৮০১৩৪৯৬৫৬০২৭',
                'designation' => 'Marketing Officer',
                'designation_bn' => 'মার্কেটিং অফিসার',
                'facebook' => 'https://www.facebook.com/share/196jqwbpyM/',
                'twitter' => 'https://twitter.com/',
                'instagram' => 'https://www.instagram.com/',
                'youtube' => 'https://www.youtube.com/',
                'experience' => '3 years',
                'experience_bn' => '৩ বছর',
                'biography' => '<p>Ashik serves as a Marketing Officer at AL FAHIM INTERNATIONAL, actively engaging with prospective workers and youth seeking overseas employment opportunities.</p><p>He provides detailed insights regarding visa processing timelines, documentation requirements, and embassy verification procedures to ensure seamless candidate transitions.</p>',
                'biography_bn' => '<p>আশিক আল ফাহিম ইন্টারন্যাশনালের মার্কেটিং অফিসার হিসেবে কাজ করছেন এবং বিদেশী কর্মসংস্থানের সুযোগ খুঁজছেন এমন যুবকদের সাথে যুক্ত আছেন।</p><p>তিনি ভিসা প্রসেসিংয়ের সময়সূচী এবং প্রয়োজনীয় কাগজপত্র সম্পর্কে বিশদ ধারণা প্রদান করেন।</p>',
                'image' => 'upload/our_team/ashik.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ),
            array(
                'id' => 14,
                'name' => 'Muntaha',
                'name_bn' => 'মুনতাহা',
                'email' => 'alfahiminternational944@gmail.com',
                'phone' => '+8801353786478',
                'phone_bn' => '+৮৮০১৩৫৩৭৮৬৪৭৮',
                'designation' => 'Marketing Officer',
                'designation_bn' => 'মার্কেটিং অফিসার',
                'facebook' => 'https://www.facebook.com/share/196jqwbpyM/',
                'twitter' => 'https://twitter.com/',
                'instagram' => 'https://www.instagram.com/',
                'youtube' => 'https://www.youtube.com/',
                'experience' => '3 years',
                'experience_bn' => '৩ বছর',
                'biography' => '<p>Muntaha is a dedicated Marketing Officer at AL FAHIM INTERNATIONAL, responsible for applicant consultations, profile assessments, and customer engagement.</p><p>She is committed to transparent communication, helping job seekers identify the best foreign career opportunities suited to their qualifications and career aspirations.</p>',
                'biography_bn' => '<p>মুনতাহা আল ফাহিম ইন্টারন্যাশনালের একজন নিবেদিত মার্কেটিং অফিসার, যিনি আবেদনকারীদের পরামর্শ এবং প্রোফাইল মূল্যায়নের দায়িত্বে আছেন।</p><p>তিনি চাকরি প্রার্থীদের তাদের যোগ্যতা অনুযায়ী সেরা বিদেশী কর্মজীবনের সুযোগ খুঁজে পেতে সহায়তা করেন।</p>',
                'image' => 'upload/our_team/muntaha.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ),
            array(
                'id' => 15,
                'name' => 'Lima Sultana',
                'name_bn' => 'লিমা সুলতানা',
                'email' => 'alfahiminternational944@gmail.com',
                'phone' => '+8801739930072',
                'phone_bn' => '+৮৮০১৭৩৯৯৩০০৭২',
                'designation' => 'Marketing Officer',
                'designation_bn' => 'মার্কেটিং অফিসার',
                'facebook' => 'https://www.facebook.com/share/196jqwbpyM/',
                'twitter' => 'https://twitter.com/',
                'instagram' => 'https://www.instagram.com/',
                'youtube' => 'https://www.youtube.com/',
                'experience' => '4 years',
                'experience_bn' => '৪ বছর',
                'biography' => '<p>Lima Sultana is an experienced Marketing Officer at AL FAHIM INTERNATIONAL with expertise in candidate counseling, foreign visa processing pathways, and career guidance.</p><p>She assists candidates across various sectors with document verification, interview preparation, and pre-departure readiness, delivering trusted and personalized support.</p>',
                'biography_bn' => '<p>লিমা সুলতানা আল ফাহিম ইন্টারন্যাশনালের একজন অভিজ্ঞ মার্কেটিং অফিসার, যিনি ভিসা প্রসেসিং এবং ক্যারিয়ার গাইডেন্সে দক্ষ।</p><p>তিনি প্রার্থীদের নথিপত্র যাচাইকরণ এবং প্রাক-প্রস্থান প্রস্তুতিতে বিশ্বস্ত সহায়তা প্রদান করেন।</p>',
                'image' => 'upload/our_team/lima_sultana.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ),
            array(
                'id' => 16,
                'name' => 'Sohag',
                'name_bn' => 'সোহাগ',
                'email' => 'alfahiminternational944@gmail.com',
                'phone' => '+880 1799-069052',
                'phone_bn' => '+৮৮০ ১৭৯৯-০৬৯০৫২',
                'designation' => 'Office Assistant',
                'designation_bn' => 'অফিস সহকারী',
                'facebook' => 'https://www.facebook.com/share/196jqwbpyM/',
                'twitter' => 'https://twitter.com/',
                'instagram' => 'https://www.instagram.com/',
                'youtube' => 'https://www.youtube.com/',
                'experience' => '3 years',
                'experience_bn' => '৩ বছর',
                'biography' => '<p>Sohag is an attentive Office Assistant at AL FAHIM INTERNATIONAL. He manages daily administrative operations, document dispatch, office logistics, and candidate assistance to maintain an orderly and efficient workplace environment.</p>',
                'biography_bn' => '<p>সোহাগ আল ফাহিম ইন্টারন্যাশনালের একজন মনোযোগী অফিস সহকারী। তিনি একটি সুশৃঙ্খল কাজের পরিবেশ বজায় রাখতে প্রতিদিনের প্রশাসনিক কাজগুলো পরিচালনা করেন।</p>',
                'image' => 'upload/our_team/sohag.jpeg',
                'created_at' => now(),
                'updated_at' => now()
            ),
        );

        // Clear existing records and reseed
        OurTeam::query()->delete();

        foreach ($ourTeams as $ourTeam) {
            OurTeam::create($ourTeam);
        }
    }
}
