<?php

namespace Database\Seeders;

use App\Models\WebsiteContent;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class WebsiteContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $website_contents = array(
            array('id' => '1', 'theme_id'=>'1','page_name' => 'Home','link_key' => 'home-seo','hints' => 'Home SEO','title' => 'AL FAHIM INTERNATIONAL - Overseas Manpower Recruitment & Work Permit Agency','title_label' => 'Meta Title','subtitle' => 'manpower agency, overseas employment, work permit visa, saudi arabia work visa, dubai work permit, malaysia calling visa, maldives work permit, romania work visa','subtitle_label' => 'Meta Keywords','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>AL FAHIM INTERNATIONAL is a leading government-approved manpower recruitment and overseas employment agency providing genuine work permit visas for Maldives, Saudi Arabia, Dubai (UAE), Malaysia, and Romania.</p>','description_label' => 'Meta Description','image' => 'upload/website-content/56374520240312091021.jpg','image_label' => 'Meta Image','created_at' => now(),'updated_at' => now()),
            array('id' => '2', 'theme_id'=>'1','page_name' => 'About','link_key' => 'about-seo','hints' => 'About SEO','title' => 'About Us - AL FAHIM INTERNATIONAL Overseas Manpower Recruitment','title_label' => 'Meta Title','subtitle' => 'about manpower agency, overseas recruitment, licensed agency, work permits','subtitle_label' => 'Meta Keywords','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Learn about AL FAHIM INTERNATIONAL, our mission, ethics, and track record in sending manpower abroad with 100% legal work permits.</p>','description_label' => 'Meta Description','image' => 'upload/website-content/81647720240312092240.jpg','image_label' => 'Meta Image','created_at' => now(),'updated_at' => now()),
            array('id' => '3', 'theme_id'=>'1','page_name' => 'Contact','link_key' => 'contact-seo','hints' => 'Contact SEO','title' => 'Contact Us - AL FAHIM INTERNATIONAL','title_label' => 'Meta Title','subtitle' => 'contact manpower agency, work permit helpline, overseas job inquiry','subtitle_label' => 'Meta Keywords','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Contact AL FAHIM INTERNATIONAL for overseas employment inquiries, work permit applications, and career counseling.</p>','description_label' => 'Meta Description','image' => 'upload/website-content/95190120240312092326.jpg','image_label' => 'Meta Image','created_at' => now(),'updated_at' => now()),
            array('id' => '4', 'theme_id'=>'1','page_name' => 'Admin Setting','link_key' => 'admin-logo','hints' => 'Admin Logo','title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'images/theme_logo.png','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '5', 'theme_id'=>'1','page_name' => 'Website Setting','link_key' => 'website-logo','hints' => 'Website Logo','title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'images/theme_logo.png','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '6', 'theme_id'=>'1','page_name' => 'Home','link_key' => 'home-hero-section','hints' => 'Home Hero Section','title' => 'Welcome to AL FAHIM INTERNATIONAL','title_label' => NULL,'subtitle' => 'Government Approved Overseas Manpower Recruitment Agency','subtitle_label' => NULL,'button_text' => 'Explore Work Permits','button_text_label' => NULL,'button_link' => '#','button_link_label' => NULL,'description' => '<p>Your trusted partner for overseas employment. Facilitating authentic Work Permit Visas for Maldives, Saudi Arabia, Dubai (UAE), Malaysia, and Romania with complete legal transparency.</p>','description_label' => NULL,'image' => 'upload/website-content/55469120240314091754.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '7', 'theme_id'=>'1','page_name' => 'Home','link_key' => 'home-hero-section','hints' => 'Home Hero Section','title' => 'Global Employment Solutions','title_label' => NULL,'subtitle' => 'Send Man Abroad with 100% Genuine Work Permits','subtitle_label' => NULL,'button_text' => 'Apply for Work Permit','button_text_label' => NULL,'button_link' => '#','button_link_label' => NULL,'description' => '<p>Fast-track work permit processing, medical fitness support, embassy visa stamping, BMET smart card clearance, and overseas deployment.</p>','description_label' => NULL,'image' => 'upload/website-content/24151320240314092657.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '8', 'theme_id'=>'1','page_name' => 'Home','link_key' => 'home-appointment-section','hints' => 'Home Appointment Section','title' => 'Job Selection & Assessment','title_label' => NULL,'subtitle' => '01','subtitle_label' => 'Number','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Explore authentic overseas job demands matching your profile, qualifications, and trade experience.</p>','description_label' => NULL,'image' => 'upload/website-content/51134920240319050519.svg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '9', 'theme_id'=>'1','page_name' => 'Home','link_key' => 'home-appointment-section','hints' => 'Home Appointment Section','title' => 'Work Permit & Medical','title_label' => NULL,'subtitle' => '02','subtitle_label' => 'Number','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Official employer work permit clearance, GAMCA/approved medical fitness checkup, and document attestation.</p>','description_label' => NULL,'image' => 'upload/website-content/40558220240319050546.svg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '10','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-appointment-section','hints' => 'Home Appointment Section','title' => 'Visa Stamping & Deployment','title_label' => NULL,'subtitle' => '03','subtitle_label' => 'Number','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Embassy visa stamping, BMET clearance, briefing, air ticketing, and smooth airport departure.</p>','description_label' => NULL,'image' => 'upload/website-content/26349720240319050557.svg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '11','theme_id'=>'1','page_name' => 'Home','link_key' => 'provider-area','hints' => 'Provider Top Area','title' => 'LEADING MANPOWER RECRUITER','title_label' => NULL,'subtitle' => 'Overseas Employment Services From','subtitle_label' => NULL,'button_text' => 'Licensed Consultants','button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '12','theme_id'=>'1','page_name' => 'Home','link_key' => 'provider-area','hints' => 'Provider Area','title' => 'We connect ambitious job seekers with verified overseas employers worldwide.','title_label' => NULL,'subtitle' => 'Our recruitment specialists manage the entire work permit cycle, ensuring 100% legal compliance and candidate safety.','subtitle_label' => NULL,'button_text' => 'Learn More','button_text_label' => NULL,'button_link' => '#','button_link_label' => NULL,'description' => '<ul>
                                                                            <li><i class="fa-regular fa-circle-check"></i>100% Genuine and Government Verified Work Permit Visas</li>
                                                                            <li><i class="fa-regular fa-circle-check"></i>Exclusive Focus on Maldives, Saudi Arabia, Dubai, Malaysia & Romania</li>
                                                                            <li><i class="fa-regular fa-circle-check"></i>Transparent Contracts with Free Accommodation & Medical Insurance</li>
                                                                            <li><i class="fa-regular fa-circle-check"></i>Complete Support with Medical, Embassy Stamping & BMET Smart Card</li>
                                                                        </ul>','description_label' => NULL,'image' => 'upload/website-content/17531220240314100106.png','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '13','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-secure-section','hints' => 'Home Secure Section','title' => 'Provide 100% Legal','title_label' => NULL,'subtitle' => 'Work Permits For You','subtitle_label' => NULL,'button_text' => 'ALL WORK PERMITS','button_text_label' => NULL,'button_link' => '#','button_link_label' => NULL,'description' => '<p>Every work permit visa processed by AL FAHIM INTERNATIONAL is backed by verified government job orders and comprehensive labor contract protections.</p>','description_label' => NULL,'image' => 'upload/website-content/278620240316043042.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '14','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-secure-slider','hints' => 'Home Secure slider','title' => 'Skilled & Technical Work Permits','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => 'View Details','button_text_label' => NULL,'button_link' => '#','button_link_label' => NULL,'description' => '<p>Placement for qualified technicians, tradesmen, machinery operators, and skilled technical professionals.</p>','description_label' => NULL,'image' => 'upload/website-content/97641220240319055426.svg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '15','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-secure-slider','hints' => 'Home Secure slider','title' => 'Industrial & Manufacturing Visas','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => 'View Details','button_text_label' => NULL,'button_link' => '#','button_link_label' => NULL,'description' => '<p>Verified employment contracts in modern industrial facilities, assembly lines, and production sectors.</p>','description_label' => NULL,'image' => 'upload/website-content/48284120240319055442.svg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '16','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-secure-slider','hints' => 'Home Secure slider','title' => 'Services & General Employment','title_label' => NULL,'subtitle' => '','subtitle_label' => NULL,'button_text' => 'View Details','button_text_label' => NULL,'button_link' => '#','button_link_label' => NULL,'description' => '<p>Reliable overseas work opportunities across hospitality, facilities management, logistics, and maintenance.</p>','description_label' => NULL,'image' => 'upload/website-content/67261720240319055459.svg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '20','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-testimonial-section','hints' => 'Home Testimonial Section','title' => 'CANDIDATE TESTIMONIALS','title_label' => NULL,'subtitle' => 'Success Stories From Abroad','subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/56745920240316053244.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '21','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-testimonial-slider','hints' => 'Home Testimonial Slider','title' => 'Mohammad Rafiq','title_label' => 'Customer Name','subtitle' => 'Saudi Arabia Work Permit','subtitle_label' => 'Visa Name','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>AL FAHIM INTERNATIONAL handled my Saudi work permit visa smoothly. From GAMCA medical to visa stamping, everything was done legally and transparently within the promised timeframe.</p>','description_label' => NULL,'image' => 'upload/website-content/91656820240316054201.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '22','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-testimonial-slider','hints' => 'Home Testimonial Slider','title' => 'Tariqul Islam','title_label' => 'Customer Name','subtitle' => 'Dubai (UAE) Work Permit','subtitle_label' => 'Visa Name','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>I received my UAE employment entry permit and job contract on time. The agency provided complete pre-departure support, flight booking, and airport guidance.</p>','description_label' => NULL,'image' => 'upload/website-content/1891020240316054507.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '23','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-testimonial-slider','hints' => 'Home Testimonial Slider','title' => 'Abdul Karim','title_label' => 'Customer Name','subtitle' => 'Malaysia Work Permit','subtitle_label' => 'Visa Name','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Very honest and professional manpower agency. My Malaysian Calling Visa was 100% genuine and the company facilities match everything stated in the contract.</p>','description_label' => NULL,'image' => 'upload/website-content/79834620240316054624.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '24','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-testimonial-slider','hints' => 'Home Testimonial Slider','title' => 'Tanvir Ahmed','title_label' => 'Customer Name','subtitle' => 'Romania Work Permit','subtitle_label' => 'Visa Name','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Securing a European work permit was a dream come true. AL FAHIM INTERNATIONAL managed my Romanian Work Permit (Aviz de Munca) and embassy visa stamping seamlessly.</p>','description_label' => NULL,'image' => 'upload/website-content/64671220240316054826.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '25','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-free-online-section','hints' => 'Home Free Online Section','title' => 'Free Overseas Job Assessment','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => 'Check Eligibility Now','button_text_label' => NULL,'button_link' => '#','button_link_label' => NULL,'description' => '<p>Consult our overseas recruitment experts to discover suitable work permit opportunities in Maldives, Saudi Arabia, Dubai, Malaysia, or Romania.</p>','description_label' => NULL,'image' => 'upload/website-content/16277520240316055438.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '26','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-choose-section','hints' => 'Home Choose Section','title' => 'WHY CHOOSE US','title_label' => NULL,'subtitle' => 'Why AL FAHIM INTERNATIONAL?','subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '27','theme_id'=>'1','page_name' => 'Home','link_key' => 'Home-choose-card','hints' => 'Home Choose Card','title' => 'Workers Deployed Abroad','title_label' => NULL,'subtitle' => '5200','subtitle_label' => 'Number','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/68483520240319053614.svg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '28','theme_id'=>'1','page_name' => 'Home','link_key' => 'Home-choose-card','hints' => 'Home Choose Card','title' => 'Verified Work Permits','title_label' => NULL,'subtitle' => '100%','subtitle_label' => 'Number','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/44343820240319053638.svg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '29','theme_id'=>'1','page_name' => 'Home','link_key' => 'Home-choose-card','hints' => 'Home Choose Card','title' => 'Target Countries','title_label' => NULL,'subtitle' => '5','subtitle_label' => 'Number','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/71742120240319053651.svg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '30','theme_id'=>'1','page_name' => 'Home','link_key' => 'Home-choose-card','hints' => 'Home Choose Card','title' => 'Years Experience','title_label' => NULL,'subtitle' => '15','subtitle_label' => 'Number','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/66833820240319053709.svg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '31','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-single-brand-section','hints' => 'Home Single Brand Section','title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/30036420240316061634.png','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '33','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-single-brand-section','hints' => 'Home Single Brand Section','title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/12470620240316061932.png','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '34','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-single-brand-section','hints' => 'Home Single Brand Section','title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/53805620240316061951.png','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '35','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-single-brand-section','hints' => 'Home Single Brand Section','title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/85108920240316062007.png','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '36','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-single-brand-section','hints' => 'Home Single Brand Section','title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/96741420240316062028.png','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '37','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-single-brand-section','hints' => 'Home Single Brand Section','title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/40476120240316062124.png','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '38','theme_id'=>'1','page_name' => 'About','link_key' => 'about-hero-section','hints' => 'About Hero Section','title' => 'About AL FAHIM INTERNATIONAL','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/48740020240316080349.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '39','theme_id'=>'1','page_name' => 'About','link_key' => 'about-unparalleled-section','hints' => 'About Unparalleled Section','title' => 'Unparalleled Manpower Consultancy from','title_label' => NULL,'subtitle' => 'Registered Recruitment Experts','subtitle_label' => NULL,'button_text' => 'Meet Our Consultants','button_text_label' => NULL,'button_link' => '#','button_link_label' => NULL,'description' => '<p>AL FAHIM INTERNATIONAL provides reliable career guidance and work permit processing backed by registered overseas employers and legal protections.</p>','description_label' => NULL,'image' => 'upload/website-content/36295520240316081027.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '40','theme_id'=>'1','page_name' => 'Service','link_key' => 'service-hero-section','hints' => 'Service Hero Section','title' => 'Our Work Permit Services','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/63705120240316083855.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '41','theme_id'=>'1','page_name' => 'Service','link_key' => 'Service-immigration-section','hints' => 'Home Immigration Section','title' => 'OVERSEAS RECRUITMENT SOLUTIONS','title_label' => NULL,'subtitle' => 'Work Permit Processing From','subtitle_label' => NULL,'button_text' => 'Licensed Manpower Specialists','button_text_label' => 'Subtitle Two','button_link' => NULL,'button_link_label' => NULL,'description' => '<p class="guid_p">We provide complete overseas employment and work permit processing for Maldives, Saudi Arabia, Dubai, Malaysia, and Romania.</p>
                                            <div class="accurate_guidance">
                                                <i class="fa-solid fa-passport"></i>
                                                <div class="guidance_cont">
                                                    <h3>Legal Work Permits</h3>
                                                    <p>All work permits and contracts are authentic, government verified, and fully legal.</p>
                                                </div>
                                            </div>
                                            <div class="accurate_guidance">
                                                <i class="fa-solid fa-plane-departure"></i>
                                                <div class="guidance_cont">
                                                    <h3>Complete Deployment</h3>
                                                    <p>From GAMCA medical to visa stamping, BMET smart card, and airport flight support.</p>
                                                </div>
                                            </div>','description_label' => NULL,'image' => 'upload/website-content/40942120240316085307.png','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '42','theme_id'=>'1','page_name' => 'Service','link_key' => 'service-tourists-section','hints' => 'Service Tourists Section','title' => 'Choose Your Destination Country','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Select from our 5 top employment destinations offering genuine work permits, verified job categories, and comprehensive employer benefits.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '43','theme_id'=>'1','page_name' => 'Contact','link_key' => 'contact-hero-section','hints' => 'Contact Hero Section','title' => 'Contact Us','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/94608120240316093652.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '44','theme_id'=>'1','page_name' => 'Contact','link_key' => 'contact-company-section','hints' => 'Contact Company Section','title' => '+880 1700 000 000','title_label' => NULL,'subtitle' => 'info@alfahiminternational.com','subtitle_label' => NULL,'button_text' => 'Dhaka, Bangladesh','button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d116834.00977793444!2d90.34928588523908!3d23.78077774431872!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755b8b087026b81%3A0x8fa563bbdd5904c2!2sDhaka%2C%20Bangladesh!5e0!3m2!1sen!2sbd!4v1709978951525!5m2!1sen!2sbd" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '45','theme_id'=>'1','page_name' => 'Blog','link_key' => 'blog-hero-section','hints' => 'Blog Hero Section','title' => 'Recruitment & Work Permit News','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/60340420240317040929.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '46','theme_id'=>'1','page_name' => 'Team','link_key' => 'team-hero-section','hints' => 'Team Hero Section','title' => 'Our Expert Team','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/76816420240317041634.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '47','theme_id'=>'1','page_name' => 'Faq','link_key' => 'faq-hero-section','hints' => 'Faq Hero Section','title' => 'Frequently Asked Questions','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/36463820240317050425.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '48','theme_id'=>'1','page_name' => 'Faq','link_key' => 'faq-accordion-top','hints' => 'Faq Accordion Top','title' => 'F A Q','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<h2>Got Questions About<strong>Work Permit Visas?</strong></h2>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '49','theme_id'=>'1','page_name' => 'Faq','link_key' => 'faq-accordion','hints' => 'Faq Accordion','title' => 'What is the processing time for a Work Permit Visa?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Processing times vary by country. Middle East countries (Saudi Arabia & UAE) typically take 3-6 weeks, Malaysia takes 4-8 weeks, while European destinations like Romania take around 2-3 months due to work permit authorization from the immigration inspectorate.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '50','theme_id'=>'1','page_name' => 'Faq','link_key' => 'faq-accordion','hints' => 'Faq Accordion','title' => 'Is medical fitness test mandatory?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Yes, medical clearance is mandatory for all destination countries. For Saudi Arabia, GAMCA approved centers are required, and for Malaysia, authorized pre-departure centers are used.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '51','theme_id'=>'1','page_name' => 'Faq','link_key' => 'faq-accordion','hints' => 'Faq Accordion','title' => 'What benefits are provided by overseas employers?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Most verified employment contracts include company-provided accommodation, health insurance, annual leave allowances, overtime compensation as per local labor law, and return flight tickets upon contract completion.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '52','theme_id'=>'1','page_name' => 'Faq','link_key' => 'faq-accordion','hints' => 'Faq Accordion','title' => 'Do you provide BMET smart card clearance?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Yes, we process government BMET (Bureau of Manpower, Employment and Training) immigration smart card clearance for all deployed workers ensuring 100% legal departure.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '53','theme_id'=>'1','page_name' => 'Faq','link_key' => 'faq-accordion','hints' => 'Faq Accordion','title' => 'How can I check the authenticity of my work permit?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>All work permits can be verified directly on official government immigration portals (such as Qiwa/Muqeem for Saudi, MOHRE for UAE, and IGI for Romania).</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '54','theme_id'=>'1','page_name' => 'Faq','link_key' => 'faq-accordion','hints' => 'Faq Accordion','title' => 'What documents are required to apply?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>You will need a valid original passport, passport-size photographs, police clearance certificate, and trade/experience certificates if applicable.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '55','theme_id'=>'1','page_name' => 'Faq','link_key' => 'faq-accordion','hints' => 'Faq Accordion','title' => 'Is prior work experience required?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Both experienced workers and fresh candidates can apply. Technical trades require relevant experience or training certificates, while general worker roles provide on-job training.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '56','theme_id'=>'1','page_name' => 'Faq','link_key' => 'faq-accordion','hints' => 'Faq Accordion','title' => 'Which countries are currently recruiting?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>We currently facilitate verified work permit opportunities for Maldives, Saudi Arabia, Dubai (UAE), Malaysia, and Romania.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '57','theme_id'=>'1','page_name' => 'Country','link_key' => NULL,'hints' => NULL,'title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '58','theme_id'=>'1','page_name' => 'Country','link_key' => 'country-hero-section','hints' => 'Country Hero Section','title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/32211420240318054429.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '59','theme_id'=>'1','page_name' => 'Country','link_key' => 'country-appoinment-section','hints' => 'Country Appoinment Section','title' => 'Overseas Job Helpline Call Us','title_label' => NULL,'subtitle' => '880 1700 000 000','subtitle_label' => 'Number','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/54956220240318054917.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '60','theme_id'=>'1','page_name' => 'Visa','link_key' => NULL,'hints' => NULL,'title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '61','theme_id'=>'1','page_name' => 'Visa','link_key' => 'visa-hero-section','hints' => 'Visa Hero Section','title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/28915120240318071310.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '63','theme_id'=>'1','page_name' => 'Terms of use','link_key' => 'terms-hero-section','hints' => 'Terms Hero Section','title' => 'Terms of Use','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/27021220240325050005.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '64','theme_id'=>'1','page_name' => 'Terms of use','link_key' => 'terms-content-section','hints' => 'Terms Content Section','title' => 'Terms and Conditions','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>AL FAHIM INTERNATIONAL operates strictly under licensed government recruitment guidelines. Candidate applications and work permit processing are governed by official foreign employment contracts and bilateral labor laws.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '65','theme_id'=>'1','page_name' => 'Terms of use','link_key' => 'terms-content-section','hints' => 'Terms Content Section','title' => 'Work Permit Verification','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>All work permits issued are subject to verification by foreign ministry labor bodies and embassy immigration channels.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '70','theme_id'=>'1','page_name' => 'Privacy Policy','link_key' => 'privacy-hero-section','hints' => 'Privacy Hero Section','title' => 'Privacy Policy','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/13607520240325051412.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '71','theme_id'=>'1','page_name' => 'Privacy Policy','link_key' => 'privacy-content-section','hints' => 'Privacy Content Section','title' => 'Candidate Data Protection','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Candidate personal documents, passports, and medical records are handled with utmost confidentiality and only submitted to authorized embassy and immigration authorities.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '77','theme_id'=>'1','page_name' => 'Cookie Policy','link_key' => 'cookie-hero-section','hints' => 'Cookie Hero Section','title' => 'Cookie Policy','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/87310720240325052335.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
            array('id' => '84','theme_id'=>'1','page_name' => 'Help Center','link_key' => 'help-hero-section','hints' => 'Help Hero Section','title' => 'Need help with Work Permits? We are here for you!','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/92805520240325061925.jpg','image_label' => NULL,'created_at' => now(),'updated_at' => now()),
        );

        foreach ($website_contents as $website_content) {
            WebsiteContent::updateOrCreate(['id' => $website_content['id']], $website_content);
        }
    }
}
