<?php

namespace Database\Seeders;

use App\Models\WebsiteContent;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class WebsiteContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $website_contents = array(
            array('id' => '1', 'theme_id'=>'1','page_name' => 'Home','link_key' => 'home-seo','hints' => 'Home SEO','title' => 'home page seo','title_label' => 'Meta Title','subtitle' => 'meta, keywords, desktop, laptop, phone, home','subtitle_label' => 'Meta Keywords','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>home meta description</p>','description_label' => 'Meta Description','image' => 'upload/website-content/56374520240312091021.jpg','image_label' => 'Meta Image','created_at' => '2024-03-13 05:42:18','updated_at' => '2024-03-13 05:42:18'),
            array('id' => '2', 'theme_id'=>'1','page_name' => 'About','link_key' => 'about-seo','hints' => 'About SEO','title' => 'about page seo','title_label' => 'Meta Title','subtitle' => 'meta, keywords, desktop, laptop, phone, home','subtitle_label' => 'Meta Keywords','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>about meta description</p>','description_label' => 'Meta Description','image' => 'upload/website-content/81647720240312092240.jpg','image_label' => 'Meta Image','created_at' => '2024-03-13 05:42:18','updated_at' => '2024-03-13 05:42:18'),
            array('id' => '3', 'theme_id'=>'1','page_name' => 'Contact','link_key' => 'contact-seo','hints' => 'Contact SEO','title' => 'contact page seo','title_label' => 'Meta Title','subtitle' => 'meta, keywords, desktop, laptop, phone, home','subtitle_label' => 'Meta Keywords','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>contact meta description</p>','description_label' => 'Meta Description','image' => 'upload/website-content/95190120240312092326.jpg','image_label' => 'Meta Image','created_at' => '2024-03-13 05:42:18','updated_at' => '2024-03-13 05:42:18'),
            array('id' => '4', 'theme_id'=>'1','page_name' => 'Admin Setting','link_key' => 'admin-logo','hints' => 'Admin Logo','title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/59332220240314072312.png','image_label' => NULL,'created_at' => '2024-03-07 06:23:21','updated_at' => '2024-03-07 06:23:21'),
            array('id' => '5', 'theme_id'=>'1','page_name' => 'Website Setting','link_key' => 'website-logo','hints' => 'Website Logo','title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/75007120240314071853.png','image_label' => NULL,'created_at' => '2024-03-07 06:23:22','updated_at' => '2024-03-07 06:23:22'),
            array('id' => '6', 'theme_id'=>'1','page_name' => 'Home','link_key' => 'home-hero-section','hints' => 'Home Hero Section','title' => 'Welcome to visapro','title_label' => NULL,'subtitle' => 'Immigration & Visa Consultant Agent','subtitle_label' => NULL,'button_text' => 'Discover More','button_text_label' => NULL,'button_link' => '#','button_link_label' => NULL,'description' => '<p>Pellentesque at posuere tellus phasellus scelerisque porem.</p>','description_label' => NULL,'image' => 'upload/website-content/55469120240314091754.jpg','image_label' => NULL,'created_at' => '2024-03-14 09:17:54','updated_at' => '2024-03-14 09:32:41'),
            array('id' => '7', 'theme_id'=>'1','page_name' => 'Home','link_key' => 'home-hero-section','hints' => 'Home Hero Section','title' => 'Welcome to visapro','title_label' => NULL,'subtitle' => 'Immigration & Visa Consultant Agent','subtitle_label' => NULL,'button_text' => 'Discover More','button_text_label' => NULL,'button_link' => '#','button_link_label' => NULL,'description' => '<p>Pellentesque at posuere tellus phasellus scelerisque porem.</p>','description_label' => NULL,'image' => 'upload/website-content/24151320240314092657.jpg','image_label' => NULL,'created_at' => '2024-03-14 09:26:57','updated_at' => '2024-03-14 09:26:57'),
            array('id' => '8', 'theme_id'=>'1','page_name' => 'Home','link_key' => 'home-appointment-section','hints' => 'Home Appointment Section','title' => 'Book an Appointment','title_label' => NULL,'subtitle' => '01','subtitle_label' => 'Number','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Cupidatat non proident sunt culpa qui officia deserunt mollit anim.</p>','description_label' => NULL,'image' => 'upload/website-content/51134920240319050519.svg','image_label' => NULL,'created_at' => '2024-03-14 09:39:06','updated_at' => '2024-03-19 05:05:19'),
            array('id' => '9', 'theme_id'=>'1','page_name' => 'Home','link_key' => 'home-appointment-section','hints' => 'Home Appointment Section','title' => 'Immigration Experts','title_label' => NULL,'subtitle' => '02','subtitle_label' => 'Number','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Cupidatat non proident sunt culpa qui officia deserunt mollit anim.</p>','description_label' => NULL,'image' => 'upload/website-content/40558220240319050546.svg','image_label' => NULL,'created_at' => '2024-03-14 09:40:53','updated_at' => '2024-03-19 05:05:46'),
            array('id' => '10','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-appointment-section','hints' => 'Home Appointment Section','title' => 'Apply Online Visa','title_label' => NULL,'subtitle' => '03','subtitle_label' => 'Number','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Cupidatat non proident sunt culpa qui officia deserunt mollit anim.</p>','description_label' => NULL,'image' => 'upload/website-content/26349720240319050557.svg','image_label' => NULL,'created_at' => '2024-03-14 09:42:43','updated_at' => '2024-03-19 05:05:57'),
            array('id' => '11','theme_id'=>'1','page_name' => 'Home','link_key' => 'provider-area','hints' => 'Provider Top Area','title' => 'THE BEST VISA PROVIDER','title_label' => NULL,'subtitle' => 'Immigration Services From','subtitle_label' => NULL,'button_text' => 'Experienced Lawyers','button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-14 10:12:10','updated_at' => '2024-03-14 10:12:10'),
            array('id' => '12','theme_id'=>'1','page_name' => 'Home','link_key' => 'provider-area','hints' => 'Provider Area','title' => 'We have been counselling students for educational opportunities in Foreign countrie.','title_label' => NULL,'subtitle' => 'There are may experienced engineer for your immigration service. We give the best immigration service for you.','subtitle_label' => NULL,'button_text' => 'Discover More','button_text_label' => NULL,'button_link' => '#','button_link_label' => NULL,'description' => '<ul>
                                                                            <li><i class="fa-regular fa-circle-check"></i>We are committed to providing quality IT Services
                                                                            </li>
                                                                            <li><i class="fa-regular fa-circle-check"></i>Our benefits are endless for local IT Companies &
                                                                                Startu</li>
                                                                            <li><i class="fa-regular fa-circle-check"></i>Processes of achieving the excellence and
                                                                                improvements</li>
                                                                            <li><i class="fa-regular fa-circle-check"></i>Our benefits are endless for local IT Companies &
                                                                                Startu</li>
                                                                        </ul>','description_label' => NULL,'image' => 'upload/website-content/17531220240314100106.png','image_label' => NULL,'created_at' => '2024-03-14 10:01:06','updated_at' => '2024-03-14 10:05:24'),
            array('id' => '13','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-secure-section','hints' => 'Home Secure Section','title' => 'Provide 100% Secure','title_label' => NULL,'subtitle' => 'Visa For You','subtitle_label' => NULL,'button_text' => 'ALL SERVICE','button_text_label' => NULL,'button_link' => '#','button_link_label' => NULL,'description' => '<p>Dolor sit amet consectetur elit sed do eiusmod tempor incididunt labore dolore magna aliqua enim minim veniam.</p>','description_label' => NULL,'image' => 'upload/website-content/278620240316043042.jpg','image_label' => NULL,'created_at' => '2024-03-16 04:30:42','updated_at' => '2024-03-16 04:30:42'),
            array('id' => '14','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-secure-slider','hints' => 'Home Secure slider','title' => 'Education Visa','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => 'Read More','button_text_label' => NULL,'button_link' => '#','button_link_label' => NULL,'description' => '<p>Nullam tincidunt augue eget dui volu tpat, vitae ultri ces lectus posuere. Duis urna lacus, efficitur non.</p>','description_label' => NULL,'image' => 'upload/website-content/97641220240319055426.svg','image_label' => NULL,'created_at' => '2024-03-16 05:05:27','updated_at' => '2024-03-16 05:05:27'),
            array('id' => '15','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-secure-slider','hints' => 'Home Secure slider','title' => 'Business Immigration','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => 'Read More','button_text_label' => NULL,'button_link' => '#','button_link_label' => NULL,'description' => '<p>Nullam tincidunt augue eget dui volu tpat, vitae ultri ces lectus posuere. Duis urna lacus, efficitur non.</p>','description_label' => NULL,'image' => 'upload/website-content/48284120240319055442.svg','image_label' => NULL,'created_at' => '2024-03-16 05:06:05','updated_at' => '2024-03-16 05:06:05'),
            array('id' => '16','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-secure-slider','hints' => 'Home Secure slider','title' => 'Skilled Immigration','title_label' => NULL,'subtitle' => '','subtitle_label' => NULL,'button_text' => 'Read More','button_text_label' => NULL,'button_link' => '#','button_link_label' => NULL,'description' => '<p>Nullam tincidunt augue eget dui volu tpat, vitae ultri ces lectus posuere. Duis urna lacus, efficitur non.</P>','description_label' => NULL,'image' => 'upload/website-content/67261720240319055459.svg','image_label' => NULL,'created_at' => '2024-03-16 05:06:41','updated_at' => '2024-03-16 05:06:41'),
            array('id' => '20','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-testimonial-section','hints' => 'Home Testimonial Section','title' => 'TESTIMONIALS','title_label' => NULL,'subtitle' => 'About Our Customer Say','subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/56745920240316053244.jpg','image_label' => NULL,'created_at' => '2024-03-16 05:23:33','updated_at' => '2024-03-16 05:32:44'),
            array('id' => '21','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-testimonial-slider','hints' => 'Home Testimonial Slider','title' => 'Ellen Erye','title_label' => 'Customer Name','subtitle' => 'France Working Visa','subtitle_label' => 'Visa Name','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don&#39;t look even slightly believable. If you are going to use a passage</p>','description_label' => NULL,'image' => 'upload/website-content/91656820240316054201.jpg','image_label' => NULL,'created_at' => '2024-03-16 05:42:01','updated_at' => '2024-03-16 05:42:01'),
            array('id' => '22','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-testimonial-slider','hints' => 'Home Testimonial Slider','title' => 'Ellen Erye','title_label' => 'Customer Name','subtitle' => 'France Working Visa','subtitle_label' => 'Visa Name','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>There are many variations of passages of Lorem Ipsum available, but the majority have&nbsp;suffered alteration in some form, by injected humour, or randomised words which don&#39;t look&nbsp;even slightly believable. If you are going to use a passage</p>','description_label' => NULL,'image' => 'upload/website-content/1891020240316054507.jpg','image_label' => NULL,'created_at' => '2024-03-16 05:45:07','updated_at' => '2024-03-16 05:45:07'),
            array('id' => '23','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-testimonial-slider','hints' => 'Home Testimonial Slider','title' => 'Ellen Erye','title_label' => 'Customer Name','subtitle' => 'France Working Visa','subtitle_label' => 'Visa Name','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>There are many variations of passages of Lorem Ipsum available, but the majority have&nbsp;suffered alteration in some form, by injected humour, or randomised words which don&#39;t look even slightly believable. If you are going to use a passage</p>','description_label' => NULL,'image' => 'upload/website-content/79834620240316054624.jpg','image_label' => NULL,'created_at' => '2024-03-16 05:46:24','updated_at' => '2024-03-16 05:46:24'),
            array('id' => '24','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-testimonial-slider','hints' => 'Home Testimonial Slider','title' => 'Ellen Erye','title_label' => 'Customer Name','subtitle' => 'France Working Visa','subtitle_label' => 'Visa Name','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don&#39;t look&nbsp;even slightly believable. If you are going to use a passage</p>','description_label' => NULL,'image' => 'upload/website-content/64671220240316054826.jpg','image_label' => NULL,'created_at' => '2024-03-16 05:48:26','updated_at' => '2024-03-16 05:48:26'),
            array('id' => '25','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-free-online-section','hints' => 'Home Free Online Section','title' => 'Free Online Visa Assessment','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => 'Get Free Assessment','button_text_label' => NULL,'button_link' => '#','button_link_label' => NULL,'description' => '<p>Dolor sit amet consectetur elit sed do eiusmod tempor incididunt labore dolore magna aliqua enim minim veniam.</p>','description_label' => NULL,'image' => 'upload/website-content/16277520240316055438.jpg','image_label' => NULL,'created_at' => '2024-03-16 05:54:38','updated_at' => '2024-03-16 05:54:38'),
            array('id' => '26','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-choose-section','hints' => 'Home Choose Section','title' => 'WHY CHOOSE US','title_label' => NULL,'subtitle' => 'Why VisaPro Immigration?','subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-16 06:01:34','updated_at' => '2024-03-16 06:01:34'),
            array('id' => '27','theme_id'=>'1','page_name' => 'Home','link_key' => 'Home-choose-card','hints' => 'Home Choose Card','title' => 'Student Visa','title_label' => NULL,'subtitle' => '680','subtitle_label' => 'Number','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/68483520240319053614.svg','image_label' => NULL,'created_at' => '2024-03-16 06:05:19','updated_at' => '2024-03-16 06:05:19'),
            array('id' => '28','theme_id'=>'1','page_name' => 'Home','link_key' => 'Home-choose-card','hints' => 'Home Choose Card','title' => 'Immigration','title_label' => NULL,'subtitle' => '480','subtitle_label' => 'Number','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/44343820240319053638.svg','image_label' => NULL,'created_at' => '2024-03-16 06:07:37','updated_at' => '2024-03-16 06:07:37'),
            array('id' => '29','theme_id'=>'1','page_name' => 'Home','link_key' => 'Home-choose-card','hints' => 'Home Choose Card','title' => 'Student Visa','title_label' => NULL,'subtitle' => '800','subtitle_label' => 'Number','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/71742120240319053651.svg','image_label' => NULL,'created_at' => '2024-03-16 06:08:31','updated_at' => '2024-03-16 06:08:31'),
            array('id' => '30','theme_id'=>'1','page_name' => 'Home','link_key' => 'Home-choose-card','hints' => 'Home Choose Card','title' => 'Immigration','title_label' => NULL,'subtitle' => '200','subtitle_label' => 'Number','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/66833820240319053709.svg','image_label' => NULL,'created_at' => '2024-03-16 06:09:14','updated_at' => '2024-03-16 06:09:14'),
            array('id' => '31','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-single-brand-section','hints' => 'Home Single Brand Section','title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/30036420240316061634.png','image_label' => NULL,'created_at' => '2024-03-16 06:16:34','updated_at' => '2024-03-16 06:16:34'),
            array('id' => '33','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-single-brand-section','hints' => 'Home Single Brand Section','title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/12470620240316061932.png','image_label' => NULL,'created_at' => '2024-03-16 06:19:32','updated_at' => '2024-03-16 06:19:32'),
            array('id' => '34','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-single-brand-section','hints' => 'Home Single Brand Section','title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/53805620240316061951.png','image_label' => NULL,'created_at' => '2024-03-16 06:19:51','updated_at' => '2024-03-16 06:19:51'),
            array('id' => '35','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-single-brand-section','hints' => 'Home Single Brand Section','title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/85108920240316062007.png','image_label' => NULL,'created_at' => '2024-03-16 06:20:07','updated_at' => '2024-03-16 06:20:07'),
            array('id' => '36','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-single-brand-section','hints' => 'Home Single Brand Section','title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/96741420240316062028.png','image_label' => NULL,'created_at' => '2024-03-16 06:20:28','updated_at' => '2024-03-16 06:20:28'),
            array('id' => '37','theme_id'=>'1','page_name' => 'Home','link_key' => 'home-single-brand-section','hints' => 'Home Single Brand Section','title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/40476120240316062124.png','image_label' => NULL,'created_at' => '2024-03-16 06:21:24','updated_at' => '2024-03-16 06:21:24'),
            array('id' => '38','theme_id'=>'1','page_name' => 'About','link_key' => 'about-hero-section','hints' => 'About Hero Section','title' => 'About Us','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/48740020240316080349.jpg','image_label' => NULL,'created_at' => '2024-03-16 08:03:49','updated_at' => '2024-03-16 08:03:49'),
            array('id' => '39','theme_id'=>'1','page_name' => 'About','link_key' => 'about-unparalleled-section','hints' => 'About Unparalleled Section','title' => 'Unparalleled Consultancy from','title_label' => NULL,'subtitle' => 'Best Experienced Lawyers','subtitle_label' => NULL,'button_text' => 'Meet With A Lawyer','button_text_label' => NULL,'button_link' => '#','button_link_label' => NULL,'description' => '<p>VisaPro gives their consultancy by a registered and experienced lawyer. For your immigration.</p>','description_label' => NULL,'image' => 'upload/website-content/36295520240316081027.jpg','image_label' => NULL,'created_at' => '2024-03-16 08:10:27','updated_at' => '2024-03-16 08:10:27'),
            array('id' => '40','theme_id'=>'1','page_name' => 'Service','link_key' => 'service-hero-section','hints' => 'Service Hero Section','title' => 'Our Service','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/63705120240316083855.jpg','image_label' => NULL,'created_at' => '2024-03-16 08:38:55','updated_at' => '2024-03-16 08:38:55'),
            array('id' => '41','theme_id'=>'1','page_name' => 'Service','link_key' => 'Service-immigration-section','hints' => 'Home Immigration Section','title' => 'THE BEST VISA PROVIDER','title_label' => NULL,'subtitle' => 'Immigration Services From','subtitle_label' => NULL,'button_text' => 'Experienced Lawyers','button_text_label' => 'Subtitle Two','button_link' => NULL,'button_link_label' => NULL,'description' => '<p class="guid_p">We provide immigration service in all over country and universities. orem semper sede tellus in ultrices. Nam hendrerit elit vel urna.</p>
                                            <div class="accurate_guidance">
                                                <i class="fa-solid fa-arrow-up-right-dots"></i>
                                                <div class="guidance_cont">
                                                    <h3>Accurate Guidance</h3>
                                                    <p>Skilled professionals are always ready to provide reliable services to our clients!</p>
                                                </div>
                                            </div>
                                            <div class="accurate_guidance">
                                                <i class="fa-solid fa-book"></i>
                                                <div class="guidance_cont">
                                                    <h3>Accurate Guidance</h3>
                                                    <p>Skilled professionals are always ready to provide reliable services to our clients!</p>
                                                </div>
                                            </div>','description_label' => NULL,'image' => 'upload/website-content/40942120240316085307.png','image_label' => NULL,'created_at' => '2024-03-16 08:53:07','updated_at' => '2024-03-16 09:18:58'),
            array('id' => '42','theme_id'=>'1','page_name' => 'Service','link_key' => 'service-tourists-section','hints' => 'Service Tourists Section','title' => 'Choose Your Visa','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Aliquam sodales justo sit amet urna auctor scelerisquinterdum leo anet tempus enim esent egetis hendrerit vel nibh vitae ornar sem velit aliquam facilisivitae finibus risus feslin is hendrerit vel nibh vitae ornar uspendisse consequat quis sem.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-16 09:25:07','updated_at' => '2024-03-16 09:25:07'),
            array('id' => '43','theme_id'=>'1','page_name' => 'Contact','link_key' => 'contact-hero-section','hints' => 'Contact Hero Section','title' => 'Contact Us','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/94608120240316093652.jpg','image_label' => NULL,'created_at' => '2024-03-16 09:36:52','updated_at' => '2024-03-16 09:36:52'),
            array('id' => '44','theme_id'=>'1','page_name' => 'Contact','link_key' => 'contact-company-section','hints' => 'Contact Company Section','title' => '+880 636 524 265,','title_label' => NULL,'subtitle' => 'yourinfo@gmail.com','subtitle_label' => NULL,'button_text' => 'Durham Street Hialeah
                                FL 33010, USA','button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d317716.6064010223!2d-0.43123910130156007!3d51.52860702046378!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47d8a00baf21de75%3A0x52963a5addd52a99!2sLondon%2C%20UK!5e0!3m2!1sen!2sbd!4v1709978951525!5m2!1sen!2sbd"  style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-16 09:41:24','updated_at' => '2024-03-16 09:41:24'),
            array('id' => '45','theme_id'=>'1','page_name' => 'Blog','link_key' => 'blog-hero-section','hints' => 'Blog Hero Section','title' => 'Blog List','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/60340420240317040929.jpg','image_label' => NULL,'created_at' => '2024-03-17 04:09:29','updated_at' => '2024-03-17 04:09:29'),
            array('id' => '46','theme_id'=>'1','page_name' => 'Team','link_key' => 'team-hero-section','hints' => 'Team Hero Section','title' => 'Our Team','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/76816420240317041634.jpg','image_label' => NULL,'created_at' => '2024-03-17 04:16:34','updated_at' => '2024-03-17 04:16:34'),
            array('id' => '47','theme_id'=>'1','page_name' => 'Faq','link_key' => 'faq-hero-section','hints' => 'Faq Hero Section','title' => 'FAQ','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/36463820240317050425.jpg','image_label' => NULL,'created_at' => '2024-03-17 05:04:25','updated_at' => '2024-03-17 05:04:25'),
            array('id' => '48','theme_id'=>'1','page_name' => 'Faq','link_key' => 'faq-accordion-top','hints' => 'Faq Accordion Top','title' => 'F A Q','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<h2>Frequently Ask Any<strong>Question Here</strong></h2>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-17 05:08:31','updated_at' => '2024-03-17 05:08:31'),
            array('id' => '49','theme_id'=>'1','page_name' => 'Faq','link_key' => 'faq-accordion','hints' => 'Faq Accordion','title' => 'Internet Things','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-17 05:14:49','updated_at' => '2024-03-17 05:14:49'),
            array('id' => '50','theme_id'=>'1','page_name' => 'Faq','link_key' => 'faq-accordion','hints' => 'Faq Accordion','title' => 'Artificial Intelligence','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-17 05:16:01','updated_at' => '2024-03-17 05:16:01'),
            array('id' => '51','theme_id'=>'1','page_name' => 'Faq','link_key' => 'faq-accordion','hints' => 'Faq Accordion','title' => 'Cloud Computing','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-17 05:16:49','updated_at' => '2024-03-17 05:16:49'),
            array('id' => '52','theme_id'=>'1','page_name' => 'Faq','link_key' => 'faq-accordion','hints' => 'Faq Accordion','title' => 'Data Analicys Things','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-17 05:17:32','updated_at' => '2024-03-17 05:17:32'),
            array('id' => '53','theme_id'=>'1','page_name' => 'Faq','link_key' => 'faq-accordion','hints' => 'Faq Accordion','title' => 'Internet Things','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-17 05:18:17','updated_at' => '2024-03-17 05:18:17'),
            array('id' => '54','theme_id'=>'1','page_name' => 'Faq','link_key' => 'faq-accordion','hints' => 'Faq Accordion','title' => 'Artificial Intelligence','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-17 05:19:06','updated_at' => '2024-03-17 05:19:06'),
            array('id' => '55','theme_id'=>'1','page_name' => 'Faq','link_key' => 'faq-accordion','hints' => 'Faq Accordion','title' => 'Cloud Computing','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-17 05:19:31','updated_at' => '2024-03-17 05:19:31'),
            array('id' => '56','theme_id'=>'1','page_name' => 'Faq','link_key' => 'faq-accordion','hints' => 'Faq Accordion','title' => 'Data Analicys Things','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-17 05:19:54','updated_at' => '2024-03-17 05:19:54'),
            array('id' => '57','theme_id'=>'1','page_name' => 'Country','link_key' => NULL,'hints' => NULL,'title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-18 05:43:05','updated_at' => '2024-03-18 05:43:05'),
            array('id' => '58','theme_id'=>'1','page_name' => 'Country','link_key' => 'country-hero-section','hints' => 'Country Hero Section','title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/32211420240318054429.jpg','image_label' => NULL,'created_at' => '2024-03-18 05:44:29','updated_at' => '2024-03-18 05:44:29'),
            array('id' => '59','theme_id'=>'1','page_name' => 'Country','link_key' => 'country-appoinment-section','hints' => 'Country Appoinment Section','title' => 'Our Appoinment Service Call Us','title_label' => NULL,'subtitle' => '123 456 7890','subtitle_label' => 'Number','button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/54956220240318054917.jpg','image_label' => NULL,'created_at' => '2024-03-18 05:49:17','updated_at' => '2024-03-18 05:49:17'),
            array('id' => '60','theme_id'=>'1','page_name' => 'Visa','link_key' => NULL,'hints' => NULL,'title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-18 07:12:02','updated_at' => '2024-03-18 07:12:02'),
            array('id' => '61','theme_id'=>'1','page_name' => 'Visa','link_key' => 'visa-hero-section','hints' => 'Visa Hero Section','title' => NULL,'title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/28915120240318071310.jpg','image_label' => NULL,'created_at' => '2024-03-18 07:13:10','updated_at' => '2024-03-18 07:13:10'),
            array('id' => '63','theme_id'=>'1','page_name' => 'Terms of use','link_key' => 'terms-hero-section','hints' => 'Terms Hero Section','title' => 'Terms of Use','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/27021220240325050005.jpg','image_label' => NULL,'created_at' => '2024-03-25 05:00:06','updated_at' => '2024-03-25 05:00:06'),
            array('id' => '64','theme_id'=>'1','page_name' => 'Terms of use','link_key' => 'terms-content-section','hints' => 'Terms Content Section','title' => 'Terms and Conditions','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>The Department of Immigration and Passport Online Visa Services website is maintained for your personal user and viewing. Access and use by you of this site constitutes acceptance by you of these terms and conditions which take effect from the date of first use.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 05:04:16','updated_at' => '2024-03-25 05:04:16'),
            array('id' => '65','theme_id'=>'1','page_name' => 'Terms of use','link_key' => 'terms-content-section','hints' => 'Terms Content Section','title' => 'Copyright','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>This page contains information on copyright and what you should do if you want to link to our website or user our news feeds.</p>

            <p>The material featured on this website is subject to copyright protection unless otherwise indicated. The material may be downloaded to file or printer for the purposes of research and private study. Any other proposed use of the material is subject to a copyright license.</p>

            <p>The permission to reproduce protected material does not extend to any material on this website, which is identified as being the copyright of a third party. Authorization to reproduce such material must be obtained from the copyright holders concerned.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 05:04:51','updated_at' => '2024-03-25 05:04:51'),
            array('id' => '66','theme_id'=>'1','page_name' => 'Terms of use','link_key' => 'terms-content-section','hints' => 'Terms Content Section','title' => 'Linking to our website','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>We welcome and encourage other website&#39;s to link to the international group: Visa Services website. You do not have to ask permission to link to our website (use of our logo is by permission). However, you must comply with the conditions below:</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 05:05:30','updated_at' => '2024-03-25 05:05:30'),
            array('id' => '67','theme_id'=>'1','page_name' => 'Terms of use','link_key' => 'terms-content-section','hints' => 'Terms Content Section','title' => 'Links to third party websites','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>If you send an email or letter to the Department of Immigration and Passport asking for information, we may need to contact other government departments to find that information. If your question is technical, we may need to pass it to our technology suppliers. We do not pass on any of your personal information when dealing with your enquiry, unless you have given us permission to do so. Once we have replied to you, we keep a record of your messages for up to six months for reference and audit purposes. After this time, it should be deleted.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 05:06:09','updated_at' => '2024-03-25 05:06:09'),
            array('id' => '68','theme_id'=>'1','page_name' => 'Terms of use','link_key' => 'terms-content-section','hints' => 'Terms Content Section','title' => 'Disclaimer','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>The information available on this site is not intended to be comprehensive and many details which are relevant to particular circumstances may have been omitted. It is not a complete statement of immigration and nationality law or policy.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 05:06:41','updated_at' => '2024-03-25 05:06:41'),
            array('id' => '70','theme_id'=>'1','page_name' => 'Privacy Policy','link_key' => 'privacy-hero-section','hints' => 'Privacy Hero Section','title' => 'Privacy and Policy','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/13607520240325051412.jpg','image_label' => NULL,'created_at' => '2024-03-25 05:14:12','updated_at' => '2024-03-25 05:14:12'),
            array('id' => '71','theme_id'=>'1','page_name' => 'Privacy Policy','link_key' => 'privacy-content-section','hints' => 'Privacy Content Section','title' => 'Privacy and Policy','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>The Home Office reserves the right to gather information relating to site usage. Any information gathered is primarily for internal use to allow us to refine and improve our customer service. Where disclosure of information to a third party is likely we will, where possible, try to ensure that this is clearly indicated. This does not affect your statutory rights.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 05:17:09','updated_at' => '2024-03-25 05:17:09'),
            array('id' => '72','theme_id'=>'1','page_name' => 'Privacy Policy','link_key' => 'privacy-content-section','hints' => 'Privacy Content Section','title' => 'Online visa applications - What information do we collect?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>We collect all the personal information you complete on the visa application electronic forms.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 05:17:34','updated_at' => '2024-03-25 05:17:34'),
            array('id' => '73','theme_id'=>'1','page_name' => 'Privacy Policy','link_key' => 'privacy-content-section','hints' => 'Privacy Content Section','title' => 'Links to external sites','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Our website contains links to our websites, both of those government departments and of other organizations. This privacy policy applies only to our site, so you should always be aware when you are moving to another site. Please read the privacy statement of any site which collects personal information.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 05:18:16','updated_at' => '2024-03-25 05:18:16'),
            array('id' => '74','theme_id'=>'1','page_name' => 'Privacy Policy','link_key' => 'privacy-content-section','hints' => 'Privacy Content Section','title' => 'Your queries','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>If you send an email or letter to the Department of Immigration and Passport asking for information, we may need to contact other government departments to find that information. If your question is technical, we may need to pass it to our technology suppliers. We do not pass on any of your personal information when dealing with your enquiry, unless you have given us permission to do so. Once we have replied to you, we keep a record of your messages for up to six months for reference and audit purposes. After this time, it should be deleted.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 05:18:51','updated_at' => '2024-03-25 05:18:51'),
            array('id' => '75','theme_id'=>'1','page_name' => 'Privacy Policy','link_key' => 'privacy-content-section','hints' => 'Privacy Content Section','title' => 'Changes to this privacy policy','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>If this privacy policy changes in any way, we will place an updated version on this page. Regularly reviewing this page ensures you are always aware of what information we collect, how we use it and under what circumstances, if any, we will share it with other parties.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 05:19:23','updated_at' => '2024-03-25 05:19:23'),
            array('id' => '77','theme_id'=>'1','page_name' => 'Cookie Policy','link_key' => 'cookie-hero-section','hints' => 'Cookie Hero Section','title' => 'Cookie Policy','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/87310720240325052335.jpg','image_label' => NULL,'created_at' => '2024-03-25 05:23:35','updated_at' => '2024-03-25 05:23:35'),
            array('id' => '78','theme_id'=>'1','page_name' => 'Cookie Policy','link_key' => 'cookie-content-section','hints' => 'Cookie Content Section','title' => 'What are cookies?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Cookies are files or pieces of information that may be stored on system or internet enabled devices of the User, when the User visits the website/s of VFS Global. VFS Global uses cookies to make the website/s simpler to use and to create more valuable experiences for you as user. VFS Global cannot identify the User personally from this information. Cookies in themselves do not identify the individual user, just the computer or mobile device you are using via a randomly generated identifying tag.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 05:25:49','updated_at' => '2024-03-25 05:25:49'),
            array('id' => '79','theme_id'=>'1','page_name' => 'Cookie Policy','link_key' => 'cookie-content-section','hints' => 'Cookie Content Section','title' => 'How VFS use cookies?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>We collect all the personal information you complete on the visa application electronic forms.</p>

            <p>Our Site may use and allow third parties to place cookies (session and persistent), pixels/tags, SDKs, application program interfaces (&quot;APIs&quot;), and other technologies (collectively, &quot;Cookies&quot;) on our Site that may collect and store certain information about you. Some of these Cookies are necessary to provide, secure, and maintain the basic functions of the Site</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 05:26:22','updated_at' => '2024-03-25 05:26:22'),
            array('id' => '80','theme_id'=>'1','page_name' => 'Cookie Policy','link_key' => 'cookie-content-section','hints' => 'Cookie Content Section','title' => 'EU/UK Site Visitors','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>Our website contains links to our websites, both of those government departments and of other organizations. This privacy policy applies only to our site, so you should always be aware when you are moving to another site. Please read the privacy statement of any site which collects personal information.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 05:26:46','updated_at' => '2024-03-25 05:26:46'),
            array('id' => '81','theme_id'=>'1','page_name' => 'Cookie Policy','link_key' => 'cookie-content-section','hints' => 'Cookie Content Section','title' => 'How to manage or opt out of Cookies from VFS Global?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>If you send an email or letter to the Department of Immigration and Passport asking for information, we may need to contact other government departments to find that information. If your question is technical, we may need to pass it to our technology suppliers. We do not pass on any of your personal information when dealing with your enquiry, unless you have given us permission to do so. Once we have replied to you, we keep a record of your messages for up to six months for reference and audit purposes. After this time, it should be deleted.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 05:27:10','updated_at' => '2024-03-25 05:27:10'),
            array('id' => '82','theme_id'=>'1','page_name' => 'Cookie Policy','link_key' => 'cookie-content-section','hints' => 'Cookie Content Section','title' => 'Changes to this privacy policy','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>If this privacy policy changes in any way, we will place an updated version on this page. Regularly reviewing this page ensures you are always aware of what information we collect, how we use it and under what circumstances, if any, we will share it with other parties.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 05:30:02','updated_at' => '2024-03-25 05:30:02'),
            array('id' => '84','theme_id'=>'1','page_name' => 'Help Center','link_key' => 'help-hero-section','hints' => 'Help Hero Section','title' => 'Need help? We\'re here for you!','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => NULL,'description_label' => NULL,'image' => 'upload/website-content/92805520240325061925.jpg','image_label' => NULL,'created_at' => '2024-03-25 06:19:25','updated_at' => '2024-03-25 06:19:25'),
            array('id' => '85','theme_id'=>'1','page_name' => 'Help Center','link_key' => 'help-booking-section','hints' => 'Help booking Section','title' => 'How can I get more information about the room or property\'s facility?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>You can find details about the property in your confirmation email or on the property detail page. For anything else, you can also contact property directly.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 06:28:03','updated_at' => '2024-03-25 06:28:03'),
            array('id' => '86','theme_id'=>'1','page_name' => 'Help Center','link_key' => 'help-booking-section','hints' => 'Help booking Section','title' => 'When do I get a confirmation email?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>You can find details about the property in your confirmation email or on the property detail page. For anything else, you can also contact property directly.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 06:28:53','updated_at' => '2024-03-25 06:28:53'),
            array('id' => '87','theme_id'=>'1','page_name' => 'Help Center','link_key' => 'help-booking-section','hints' => 'Help booking Section','title' => 'Where can I check my booking details and status?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>You can find details about the property in your confirmation email or on the property detail page. For anything else, you can also contact property directly.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 06:30:05','updated_at' => '2024-03-25 06:30:05'),
            array('id' => '88','theme_id'=>'1','page_name' => 'Help Center','link_key' => 'help-cancel-section','hints' => 'Help Cancel Section','title' => 'How can I get more information about the room or property\'s facility?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>You can find details about the property in your confirmation email or on the property detail page. For anything else, you can also contact property directly.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 06:50:30','updated_at' => '2024-03-25 06:50:30'),
            array('id' => '89','theme_id'=>'1','page_name' => 'Help Center','link_key' => 'help-cancel-section','hints' => 'Help Cancel Section','title' => 'When do I get a confirmation email?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>You can find details about the property in your confirmation email or on the property detail page. For anything else, you can also contact property directly.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 06:51:26','updated_at' => '2024-03-25 06:51:26'),
            array('id' => '90','theme_id'=>'1','page_name' => 'Help Center','link_key' => 'help-cancel-section','hints' => 'Help Cancel Section','title' => 'Where can I check my booking details and status?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>You can find details about the property in your confirmation email or on the property detail page. For anything else, you can also contact property directly.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 06:52:17','updated_at' => '2024-03-25 06:52:17'),
            array('id' => '91','theme_id'=>'1','page_name' => 'Help Center','link_key' => 'help-change-section','hints' => 'Help Change Section','title' => 'How can I get more information about the room or property\'s facility?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>You can find details about the property in your confirmation email or on the property detail page. For anything else, you can also contact property directly.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 06:56:54','updated_at' => '2024-03-25 06:56:54'),
            array('id' => '92','theme_id'=>'1','page_name' => 'Help Center','link_key' => 'help-change-section','hints' => 'Help Change Section','title' => 'When do I get a confirmation email?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>You can find details about the property in your confirmation email or on the property detail page. For anything else, you can also contact property directly.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 06:58:03','updated_at' => '2024-03-25 06:58:03'),
            array('id' => '93','theme_id'=>'1','page_name' => 'Help Center','link_key' => 'help-change-section','hints' => 'Help Change Section','title' => 'Where can I check my booking details and status?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>You can find details about the property in your confirmation email or on the property detail page. For anything else, you can also contact property directly.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 06:58:44','updated_at' => '2024-03-25 06:58:44'),
            array('id' => '94','theme_id'=>'1','page_name' => 'Help Center','link_key' => 'help-special -section','hints' => 'Help Special  Section','title' => 'How can I get more information about the room or property\'s facility?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>You can find details about the property in your confirmation email or on the property detail page. For anything else, you can also contact property directly.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 07:02:16','updated_at' => '2024-03-25 07:02:16'),
            array('id' => '95','theme_id'=>'1','page_name' => 'Help Center','link_key' => 'help-special -section','hints' => 'Help Special  Section','title' => 'When do I get a confirmation email?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>You can find details about the property in your confirmation email or on the property detail page. For anything else, you can also contact property directly.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 07:03:09','updated_at' => '2024-03-25 07:03:09'),
            array('id' => '96','theme_id'=>'1','page_name' => 'Help Center','link_key' => 'help-special -section','hints' => 'Help Special  Section','title' => 'Where can I check my booking details and status?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>You can find details about the property in your confirmation email or on the property detail page. For anything else, you can also contact property directly.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 07:03:48','updated_at' => '2024-03-25 07:03:48'),
            array('id' => '97','theme_id'=>'1','page_name' => 'Help Center','link_key' => 'help-price-section','hints' => 'Help Price Section','title' => 'How can I get more information about the room or property\'s facility?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>You can find details about the property in your confirmation email or on the property detail page. For anything else, you can also contact property directly.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 07:07:54','updated_at' => '2024-03-25 07:07:54'),
            array('id' => '98','theme_id'=>'1','page_name' => 'Help Center','link_key' => 'help-price-section','hints' => 'Help Price Section','title' => 'When do I get a confirmation email?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>You can find details about the property in your confirmation email or on the property detail page. For anything else, you can also contact property directly.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 07:08:59','updated_at' => '2024-03-25 07:08:59'),
            array('id' => '99','theme_id'=>'1','page_name' => 'Help Center','link_key' => 'help-price-section','hints' => 'Help Price Section','title' => 'Where can I check my booking details and status?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>You can find details about the property in your confirmation email or on the property detail page. For anything else, you can also contact property directly.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 07:09:57','updated_at' => '2024-03-25 07:09:57'),
            array('id' => '100','theme_id'=>'1','page_name' => 'Help Center','link_key' => 'help-fast-section','hints' => 'Help Fast Section','title' => 'How can I get more information about the room or property\'s facility?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>You can find details about the property in your confirmation email or on the property detail page. For anything else, you can also contact property directly.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 07:13:39','updated_at' => '2024-03-25 07:13:39'),
            array('id' => '101','theme_id'=>'1','page_name' => 'Help Center','link_key' => 'help-fast-section','hints' => 'Help Fast Section','title' => 'When do I get a confirmation email?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>You can find details about the property in your confirmation email or on the property detail page. For anything else, you can also contact property directly.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 07:16:00','updated_at' => '2024-03-25 07:16:00'),
            array('id' => '102','theme_id'=>'1','page_name' => 'Help Center','link_key' => 'help-fast-section','hints' => 'Help Fast Section','title' => 'Where can I check my booking details and status?','title_label' => NULL,'subtitle' => NULL,'subtitle_label' => NULL,'button_text' => NULL,'button_text_label' => NULL,'button_link' => NULL,'button_link_label' => NULL,'description' => '<p>You can find details about the property in your confirmation email or on the property detail page. For anything else, you can also contact property directly.</p>','description_label' => NULL,'image' => NULL,'image_label' => NULL,'created_at' => '2024-03-25 07:16:44','updated_at' => '2024-03-25 07:16:44')
        );
        foreach ($website_contents as $website_content) {
            WebsiteContent::create($website_content);
        }
          
    }
}
