<?php

namespace Database\Seeders;

use App\Models\WebsiteContent;
use Illuminate\Database\Seeder;

class WebsiteContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $website_contents = [
            // ==================== HOME SEO ====================
            [
                'id' => '1',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-seo',
                'hints' => 'Home SEO',
                'title' => 'AL FAHIM INTERNATIONAL - Government Approved Overseas Manpower Recruitment & Work Permit Agency',
                'title_label' => 'Meta Title',
                'subtitle' => 'overseas manpower agency, work permit visa, saudi arabia work visa, uae employment visa, malaysia calling visa, maldives work permit, romania work visa, bmet smart card agency dhaka',
                'subtitle_label' => 'Meta Keywords',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p>AL FAHIM INTERNATIONAL is an authorized, government-approved overseas manpower recruitment agency (License No. RL-XXXX) specializing in genuine work permit processing and legal worker deployment for Saudi Arabia, UAE, Maldives, Malaysia, and Romania.</p>',
                'description_label' => 'Meta Description',
                'image' => 'upload/website-content/56374520240312091021.jpg',
                'image_label' => 'Meta Image',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== ABOUT SEO ====================
            [
                'id' => '2',
                'theme_id' => '1',
                'page_name' => 'About',
                'link_key' => 'about-seo',
                'hints' => 'About SEO',
                'title' => 'About Us - AL FAHIM INTERNATIONAL Overseas Manpower Recruitment Agency',
                'title_label' => 'Meta Title',
                'subtitle' => 'about manpower agency, licensed recruiting agency dhaka, bmet approved, baira member, ethical overseas recruitment, work permit processing',
                'subtitle_label' => 'Meta Keywords',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p>Discover AL FAHIM INTERNATIONAL, an authorized overseas manpower recruitment agency dedicated to ethical migration, worker welfare, and legal work permits for Saudi Arabia, UAE, Maldives, Malaysia, and Romania.</p>',
                'description_label' => 'Meta Description',
                'image' => 'upload/website-content/81647720240312092240.jpg',
                'image_label' => 'Meta Image',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== CONTACT SEO ====================
            [
                'id' => '3',
                'theme_id' => '1',
                'page_name' => 'Contact',
                'link_key' => 'contact-seo',
                'hints' => 'Contact SEO',
                'title' => 'Contact Us - AL FAHIM INTERNATIONAL Manpower Recruitment Helpline',
                'title_label' => 'Meta Title',
                'subtitle' => 'contact manpower agency, work permit helpline dhaka, overseas job consultation, bmet enquiry',
                'subtitle_label' => 'Meta Keywords',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p>Contact AL FAHIM INTERNATIONAL in Dhaka, Bangladesh for authentic work permit inquiries, trade test appointments, and overseas job deployment status.</p>',
                'description_label' => 'Meta Description',
                'image' => 'upload/website-content/95190120240312092326.jpg',
                'image_label' => 'Meta Image',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== LOGOS ====================
            [
                'id' => '4',
                'theme_id' => '1',
                'page_name' => 'Admin Setting',
                'link_key' => 'admin-logo',
                'hints' => 'Admin Logo',
                'title' => null,
                'title_label' => null,
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'images/theme_logo.png',
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '5',
                'theme_id' => '1',
                'page_name' => 'Website Setting',
                'link_key' => 'website-logo',
                'hints' => 'Website Logo',
                'title' => null,
                'title_label' => null,
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'images/theme_logo.png',
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== HOME HERO SECTION ====================
            [
                'id' => '6',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-hero-section',
                'hints' => 'Home Hero Slide 1',
                'title' => 'Welcome to AL FAHIM INTERNATIONAL',
                'title_label' => 'Slide Title',
                'subtitle' => 'Government Approved Overseas Manpower Recruitment Agency (RL-XXXX)',
                'subtitle_label' => 'Slide Subtitle',
                'button_text' => 'Explore Work Permits',
                'button_text_label' => 'Button Text',
                'button_link' => '/service',
                'button_link_label' => 'Button Link',
                'description' => '<p>Your trusted partner for authentic overseas employment. Facilitating 100% legal Work Permit Visas for Saudi Arabia, UAE, Maldives, Malaysia, and Romania with direct employer quotas, verified contracts, and full BMET emigration clearance.</p>',
                'description_label' => 'Slide Description',
                'image' => 'upload/website-content/55469120240314091754.jpg',
                'image_label' => 'Slide Image',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-hero-section',
                'hints' => 'Home Hero Slide 2',
                'title' => 'Global Workforce Deployment',
                'title_label' => 'Slide Title',
                'subtitle' => 'Empowering Bangladeshi Workers with 100% Legal Work Permits',
                'subtitle_label' => 'Slide Subtitle',
                'button_text' => 'Apply for Work Permit',
                'button_text_label' => 'Button Text',
                'button_link' => '/apply',
                'button_link_label' => 'Button Link',
                'description' => '<p>End-to-end recruitment solutions: certified trade testing, Wafid/GAMCA bio-medical screening, embassy visa stamping, BMET Smart Card clearance, and smooth pre-departure flight deployment.</p>',
                'description_label' => 'Slide Description',
                'image' => 'upload/website-content/24151320240314092657.jpg',
                'image_label' => 'Slide Image',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== HOME 3-STEP APPOINTMENT SECTION ====================
            [
                'id' => '8',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-appointment-section',
                'hints' => 'Step 1',
                'title' => 'Trade Testing & Profile Selection',
                'title_label' => 'Step Title',
                'subtitle' => '01',
                'subtitle_label' => 'Step Number',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p>Comprehensive skill assessment, candidate profiling, and matching with verified overseas employer job quotas.</p>',
                'description_label' => 'Step Description',
                'image' => 'upload/website-content/51134920240319050519.svg',
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '9',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-appointment-section',
                'hints' => 'Step 2',
                'title' => 'Bio-Medical & Work Permit Clearance',
                'title_label' => 'Step Title',
                'subtitle' => '02',
                'subtitle_label' => 'Step Number',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p>Wafid/GAMCA authorized medical fitness tests, digital contract verification, and official work permit approval.</p>',
                'description_label' => 'Step Description',
                'image' => 'upload/website-content/40558220240319050546.svg',
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '10',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-appointment-section',
                'hints' => 'Step 3',
                'title' => 'Embassy Stamping & BMET Deployment',
                'title_label' => 'Step Title',
                'subtitle' => '03',
                'subtitle_label' => 'Step Number',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p>Embassy visa endorsement, BMET Smart Card emigration clearance, orientation briefing, and airport departure.</p>',
                'description_label' => 'Step Description',
                'image' => 'upload/website-content/26349720240319050557.svg',
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== HOME & ABOUT PROVIDER AREA ====================
            [
                'id' => '11',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'provider-area',
                'hints' => 'Provider Top Area',
                'title' => 'GOVERNMENT APPROVED RECRUITMENT AGENCY',
                'title_label' => 'Badge / Tagline',
                'subtitle' => 'Overseas Manpower & Work Permit Solutions From',
                'subtitle_label' => 'Section Subtitle',
                'button_text' => 'Licensed Recruitment Specialists',
                'button_text_label' => 'Title Highlight',
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => null,
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '12',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'provider-area',
                'hints' => 'Provider Area Content',
                'title' => 'Connecting Qualified Bangladeshi Workforce with Verified Overseas Employers Worldwide',
                'title_label' => 'Main Heading',
                'subtitle' => 'From Dhaka technical assessment to destination airport reception, our licensed officers manage the full deployment cycle ensuring complete legal compliance and worker protection.',
                'subtitle_label' => 'Paragraph Lead',
                'button_text' => 'About Our Agency',
                'button_text_label' => 'Button Text',
                'button_link' => '/about',
                'button_link_label' => 'Button Link',
                'description' => '<ul>
    <li><i class="fa-regular fa-circle-check"></i> 100% Genuine, Government-Verified Work Permit Visas</li>
    <li><i class="fa-regular fa-circle-check"></i> Direct Employer Quotas in Saudi Arabia, UAE, Maldives, Malaysia & Romania</li>
    <li><i class="fa-regular fa-circle-check"></i> Transparent Electronic Contracts with Guaranteed Housing & Health Insurance</li>
    <li><i class="fa-regular fa-circle-check"></i> Full Assistance with Bio-Medical Tests, Embassy Visa Stamping & BMET Smart Card</li>
</ul>',
                'description_label' => 'Bullet List',
                'image' => 'upload/website-content/17531220240314100106.png',
                'image_label' => 'Featured Image',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== HOME SECURE WORK PERMITS SECTION ====================
            [
                'id' => '13',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-secure-section',
                'hints' => 'Secure Section Header',
                'title' => '100% Government Verified',
                'title_label' => 'Heading',
                'subtitle' => 'Work Permits & Overseas Quotas',
                'subtitle_label' => 'Subtitle',
                'button_text' => 'ALL WORK PERMITS',
                'button_text_label' => 'Button Text',
                'button_link' => '/service',
                'button_link_label' => 'Button Link',
                'description' => '<p>Every work permit visa processed by AL FAHIM INTERNATIONAL is backed by authenticated corporate demand letters, embassy attestation, and statutory labor protections.</p>',
                'description_label' => 'Description',
                'image' => 'upload/website-content/278620240316043042.jpg',
                'image_label' => 'Background Image',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '14',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-secure-slider',
                'hints' => 'Work Permit Category 1',
                'title' => 'Skilled & Technical Work Permits',
                'title_label' => 'Category Title',
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => 'View Details',
                'button_text_label' => 'Button Text',
                'button_link' => '/service',
                'button_link_label' => 'Button Link',
                'description' => '<p>Placement for certified welders, electricians, HVAC mechanics, heavy machinery operators, and engineering tradesmen.</p>',
                'description_label' => 'Category Description',
                'image' => 'upload/website-content/97641220240319055426.svg',
                'image_label' => 'Icon Image',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '15',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-secure-slider',
                'hints' => 'Work Permit Category 2',
                'title' => 'Industrial & Factory Work Permits',
                'title_label' => 'Category Title',
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => 'View Details',
                'button_text_label' => 'Button Text',
                'button_link' => '/service',
                'button_link_label' => 'Button Link',
                'description' => '<p>Verified employment contracts in electronics assembly, automotive manufacturing, food packaging, and metal fabrication.</p>',
                'description_label' => 'Category Description',
                'image' => 'upload/website-content/48284120240319055442.svg',
                'image_label' => 'Icon Image',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '16',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-secure-slider',
                'hints' => 'Work Permit Category 3',
                'title' => 'Hospitality & Facility Work Permits',
                'title_label' => 'Category Title',
                'subtitle' => '',
                'subtitle_label' => null,
                'button_text' => 'View Details',
                'button_text_label' => 'Button Text',
                'button_link' => '/service',
                'button_link_label' => 'Button Link',
                'description' => '<p>Reliable vacancies in 5-star island resorts, hotel operations, corporate facility maintenance, and warehousing logistics.</p>',
                'description_label' => 'Category Description',
                'image' => 'upload/website-content/67261720240319055459.svg',
                'image_label' => 'Icon Image',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== TESTIMONIALS ====================
            [
                'id' => '20',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-testimonial-section',
                'hints' => 'Testimonial Header',
                'title' => 'CANDIDATE SUCCESS STORIES',
                'title_label' => 'Tagline',
                'subtitle' => 'Verified Workers Deployed Overseas',
                'subtitle_label' => 'Heading',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'upload/website-content/56745920240316053244.jpg',
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '21',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-testimonial-slider',
                'hints' => 'Testimonial 1',
                'title' => 'Mohammad Rafiqul Islam',
                'title_label' => 'Candidate Name',
                'subtitle' => 'Saudi Arabia — Structural Welder (SAR 2,800/mo)',
                'subtitle_label' => 'Placement Details',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p>AL FAHIM INTERNATIONAL managed my Saudi employment visa through the Qiwa portal. From GAMCA medical to BMET smart card, everything was 100% legal, on time, and strictly matched the contract terms.</p>',
                'description_label' => 'Review Text',
                'image' => 'upload/website-content/91656820240316054201.jpg',
                'image_label' => 'Candidate Photo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '22',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-testimonial-slider',
                'hints' => 'Testimonial 2',
                'title' => 'Tariqul Hasan',
                'title_label' => 'Candidate Name',
                'subtitle' => 'UAE (Dubai) — Commercial HVAC Technician (AED 2,600/mo)',
                'subtitle_label' => 'Placement Details',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p>I received my MoHRE standardized offer letter and UAE entry permit within 25 days. The agency handled airport briefing, ticket booking, and my employer provided modern air-conditioned accommodation.</p>',
                'description_label' => 'Review Text',
                'image' => 'upload/website-content/1891020240316054507.jpg',
                'image_label' => 'Candidate Photo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '23',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-testimonial-slider',
                'hints' => 'Testimonial 3',
                'title' => 'Abdul Karim Mia',
                'title_label' => 'Candidate Name',
                'subtitle' => 'Malaysia — Electronics Assembly Technician (RM 1,850/mo)',
                'subtitle_label' => 'Placement Details',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p>Outstanding manpower agency. My Malaysian Calling Visa (VDR) had an authentic immigration QR code. Working in Penang now with SOCSO insurance and regular monthly overtime pay.</p>',
                'description_label' => 'Review Text',
                'image' => 'upload/website-content/79834620240316054624.jpg',
                'image_label' => 'Candidate Photo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '24',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-testimonial-slider',
                'hints' => 'Testimonial 4',
                'title' => 'Tanvir Ahmed Chowdhury',
                'title_label' => 'Candidate Name',
                'subtitle' => 'Romania — Industrial Machine Operator (€950/mo)',
                'subtitle_label' => 'Placement Details',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p>Securing a legal European work permit was a life-changing milestone. AL FAHIM processed my Romanian Aviz de Munca and Embassy visa smoothly. Now legally working in Bucharest under EU labor protections.</p>',
                'description_label' => 'Review Text',
                'image' => 'upload/website-content/64671220240316054826.jpg',
                'image_label' => 'Candidate Photo',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== HOME ASSESSMENT CTA ====================
            [
                'id' => '25',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-free-online-section',
                'hints' => 'Assessment CTA Section',
                'title' => 'Free Overseas Job Assessment & Trade Verification',
                'title_label' => 'Heading',
                'subtitle' => 'Find Your Next Global Career',
                'subtitle_label' => 'Subtitle',
                'button_text' => 'Check Eligibility Now',
                'button_text_label' => 'Button Text',
                'button_link' => '/apply',
                'button_link_label' => 'Button Link',
                'description' => '<p>Consult our licensed consular specialists to verify your eligibility for active employer quotas across Saudi Arabia, UAE, Maldives, Malaysia, and Romania.</p>',
                'description_label' => 'Description',
                'image' => 'upload/website-content/16277520240316055438.jpg',
                'image_label' => 'Banner Image',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== HOME & ABOUT CHOOSE / COUNTERS ====================
            [
                'id' => '26',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-choose-section',
                'hints' => 'Why Choose Us Header',
                'title' => 'WHY CHOOSE US',
                'title_label' => 'Tagline',
                'subtitle' => 'Proven Track Record in Overseas Deployment',
                'subtitle_label' => 'Heading',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => null,
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '27',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'Home-choose-card',
                'hints' => 'Counter 1',
                'title' => 'Workers Legally Deployed Abroad',
                'title_label' => 'Card Title',
                'subtitle' => '15000+',
                'subtitle_label' => 'Count Number',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'upload/website-content/68483520240319053614.svg',
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '28',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'Home-choose-card',
                'hints' => 'Counter 2',
                'title' => 'Government Verified Work Permits',
                'title_label' => 'Card Title',
                'subtitle' => '100%',
                'subtitle_label' => 'Count Number',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'upload/website-content/44343820240319053638.svg',
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '29',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'Home-choose-card',
                'hints' => 'Counter 3',
                'title' => 'Primary Destination Countries',
                'title_label' => 'Card Title',
                'subtitle' => '5',
                'subtitle_label' => 'Count Number',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'upload/website-content/71742120240319053651.svg',
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '30',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'Home-choose-card',
                'hints' => 'Counter 4',
                'title' => 'Years Recruitment Excellence',
                'title_label' => 'Card Title',
                'subtitle' => '15+',
                'subtitle_label' => 'Count Number',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'upload/website-content/66833820240319053709.svg',
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== BRAND PARTNERS ====================
            [
                'id' => '31',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-single-brand-section',
                'hints' => 'Partner Brand 1',
                'title' => null,
                'title_label' => null,
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'upload/website-content/30036420240316061634.png',
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '33',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-single-brand-section',
                'hints' => 'Partner Brand 2',
                'title' => null,
                'title_label' => null,
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'upload/website-content/12470620240316061932.png',
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '34',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-single-brand-section',
                'hints' => 'Partner Brand 3',
                'title' => null,
                'title_label' => null,
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'upload/website-content/53805620240316061951.png',
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '35',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-single-brand-section',
                'hints' => 'Partner Brand 4',
                'title' => null,
                'title_label' => null,
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'upload/website-content/85108920240316062007.png',
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '36',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-single-brand-section',
                'hints' => 'Partner Brand 5',
                'title' => null,
                'title_label' => null,
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'upload/website-content/96741420240316062028.png',
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '37',
                'theme_id' => '1',
                'page_name' => 'Home',
                'link_key' => 'home-single-brand-section',
                'hints' => 'Partner Brand 6',
                'title' => null,
                'title_label' => null,
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'upload/website-content/40476120240316062124.png',
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== ABOUT PAGE SECTIONS ====================
            [
                'id' => '38',
                'theme_id' => '1',
                'page_name' => 'About',
                'link_key' => 'about-hero-section',
                'hints' => 'About Hero Section',
                'title' => 'About AL FAHIM INTERNATIONAL',
                'title_label' => 'Page Title',
                'subtitle' => 'Government Approved Overseas Manpower Recruitment Agency (RL-XXXX)',
                'subtitle_label' => 'Subtitle',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'upload/website-content/48740020240316080349.jpg',
                'image_label' => 'Hero Banner',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '39',
                'theme_id' => '1',
                'page_name' => 'About',
                'link_key' => 'about-unparalleled-section',
                'hints' => 'About Unparalleled Banner',
                'title' => 'Ethical Recruitment & Certified Deployments by',
                'title_label' => 'Title Top',
                'subtitle' => 'Registered Recruitment Experts',
                'subtitle_label' => 'Title Highlight',
                'button_text' => 'Meet Our Experts',
                'button_text_label' => 'Button Text',
                'button_link' => '#experts',
                'button_link_label' => 'Button Link',
                'description' => '<p>AL FAHIM INTERNATIONAL stands resolutely against unauthorized middlemen and fraudulent visa claims. Backed by an active government recruiting license and direct bilateral relations with employers, we protect your career, savings, and family future.</p>',
                'description_label' => 'Banner Description',
                'image' => 'upload/website-content/36295520240316081027.jpg',
                'image_label' => 'Background Banner',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '101',
                'theme_id' => '1',
                'page_name' => 'About',
                'link_key' => 'about-company-info',
                'hints' => 'About Company Info',
                'title' => 'Official Agency Profile & Operational Standards',
                'title_label' => 'Section Heading',
                'subtitle' => 'Government Approved Overseas Manpower Agency (RL-XXXX)',
                'subtitle_label' => 'Section Tagline',
                'button_text' => 'Verify Licensing',
                'button_text_label' => 'Button Text',
                'button_link' => '#licences',
                'button_link_label' => 'Button Link',
                'description' => '<p class="lead">AL FAHIM INTERNATIONAL is a premier, government-authorized overseas manpower recruitment agency headquartered in Dhaka, Bangladesh (Recruiting License No. RL-XXXX). Established with the foundational mandate of providing dignified, safe, and 100% legal foreign employment, our agency bridges the human resource requirements of leading international enterprises with the hardworking talent of Bangladeshi workers.</p>
<p>Operating under the strict statutory oversight of the <strong>Ministry of Expatriates\' Welfare and Overseas Employment</strong> and the <strong>Bureau of Manpower, Employment and Training (BMET)</strong>, our agency manages the full spectrum of international labor mobilization: trade testing, government-accredited bio-medical fitness screening, electronic contract validation, embassy visa endorsement, BMET Smart Card emigration clearance, and destination airport reception.</p>
<p>We maintain dedicated overseas desks focusing exclusively on five powerhouse destination countries: <strong>Saudi Arabia, United Arab Emirates, Republic of Maldives, Malaysia, and Romania</strong>. By maintaining direct corporate partnerships with verified giga-project contractors, multinational manufacturers, and 5-star island resort conglomerates, we guarantee zero intermediaries, genuine employer quotas, and guaranteed wage protection for every deployed candidate.</p>',
                'description_label' => 'Company Profile Content',
                'image' => 'frontend/images/about.png',
                'image_label' => 'Profile Image',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '102',
                'theme_id' => '1',
                'page_name' => 'About',
                'link_key' => 'about-ceo-speech',
                'hints' => 'CEO Speech / MD Message',
                'title' => 'A Message from Our Managing Director',
                'title_label' => 'Section Heading',
                'subtitle' => 'Fahim Al Hasan — Founder & Managing Director',
                'subtitle_label' => 'Director Title',
                'button_text' => 'Member, BAIRA',
                'button_text_label' => 'Credential Tag',
                'button_link' => '#licences',
                'button_link_label' => 'Button Link',
                'description' => '<blockquote>
    <p>"Foreign remittance is the economic backbone of Bangladesh. Behind every single remittance transfer is an honest worker striving to build a prosperous future for their children and family. To us at AL FAHIM INTERNATIONAL, overseas recruitment is never a transaction; it is a sacred trust. Our commitment has always been uncompromising: zero fraud, complete legal transparency, direct employer contracts, and total worker protection from our Dhaka testing facility to the jobsite abroad."</p>
    <cite>— Fahim Al Hasan, Managing Director & Licensee (RL-XXXX)</cite>
</blockquote>
<p>When we established AL FAHIM INTERNATIONAL over a decade ago, our objective was clear: to counter the widespread issue of unauthorized middlemen, hidden recruitment fees, and counterfeit work permits by creating an institutional standard of absolute honesty and digital verification.</p>
<p>Today, every worker deployed through our agency holds an electronic employment contract verifiable on destination government portals—including Saudi Qiwa, UAE MoHRE, Maldives Xpat, Malaysia FWCMS, and Romania IGI. We take immense pride in having empowered over 15,000 families with dignified global employment, and we remain dedicated to upholding the highest standards of international labor mobility.</p>',
                'description_label' => 'Speech Text',
                'image' => 'upload/our_team/20240319041954.jpg',
                'image_label' => 'Director Photo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '103',
                'theme_id' => '1',
                'page_name' => 'About',
                'link_key' => 'about-mission-vision',
                'hints' => 'Mission & Vision Header',
                'title' => 'OUR COMMITMENT & PRINCIPLES',
                'title_label' => 'Section Pre-title',
                'subtitle' => 'Mission, Vision & Core Values',
                'subtitle_label' => 'Section Heading',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => null,
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '111',
                'theme_id' => '1',
                'page_name' => 'About',
                'link_key' => 'about-mission-card',
                'hints' => 'Our Mission',
                'title' => 'Our Mission',
                'title_label' => 'Card Title',
                'subtitle' => 'Legal Work Permits, Trade Testing, Safe Migration',
                'subtitle_label' => 'Keywords / Tags (comma separated)',
                'button_text' => 'Standard',
                'button_text_label' => 'Card Style (highlight or standard)',
                'button_link' => 'fa-solid fa-bullseye',
                'button_link_label' => 'Icon Class',
                'description' => 'To empower Bangladeshi skilled, semi-skilled, and professional workers with secure, legally validated overseas employment opportunities, while supplying global employers with disciplined, trade-tested personnel matching exact project specifications.',
                'description_label' => 'Card Description',
                'image' => 'upload/website-content/award.svg',
                'image_label' => 'Optional Badge / Icon Image',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '112',
                'theme_id' => '1',
                'page_name' => 'About',
                'link_key' => 'about-mission-card',
                'hints' => 'Our Vision',
                'title' => 'Our Vision',
                'title_label' => 'Card Title',
                'subtitle' => 'Zero Deception, Worker Dignity, Remittance Growth',
                'subtitle_label' => 'Keywords / Tags (comma separated)',
                'button_text' => 'highlight',
                'button_text_label' => 'Card Style (highlight or standard)',
                'button_link' => 'fa-solid fa-compass',
                'button_link_label' => 'Icon Class',
                'description' => 'To stand as Bangladesh\'s most dependable and ethically revered international manpower consultancy, eradicating predatory recruitment practices, safeguarding worker dignity, and maximizing national remittance growth through lawful channels.',
                'description_label' => 'Card Description',
                'image' => 'upload/website-content/world.svg',
                'image_label' => 'Optional Badge / Icon Image',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '113',
                'theme_id' => '1',
                'page_name' => 'About',
                'link_key' => 'about-mission-card',
                'hints' => 'Core Values',
                'title' => 'Core Values & Ethics',
                'title_label' => 'Card Title',
                'subtitle' => 'BMET Compliant, Wage Security, 24/7 Welfare',
                'subtitle_label' => 'Keywords / Tags (comma separated)',
                'button_text' => 'Standard',
                'button_text_label' => 'Card Style (highlight or standard)',
                'button_link' => 'fa-solid fa-shield-halved',
                'button_link_label' => 'Icon Class',
                'description' => 'Total transparency in costs, strict compliance with the Ministry of Expatriates\' Welfare & BMET regulations, fair wage protection, and end-to-end welfare monitoring from pre-departure orientation to overseas workplace integration.',
                'description_label' => 'Card Description',
                'image' => 'upload/website-content/handshake.svg',
                'image_label' => 'Optional Badge / Icon Image',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '104',
                'theme_id' => '1',
                'page_name' => 'About',
                'link_key' => 'about-licence-cert',
                'hints' => 'Accreditations Header',
                'title' => 'OFFICIAL RECOGNITIONS',
                'title_label' => 'Section Pre-title',
                'subtitle' => 'Government Licences & International Accreditations',
                'subtitle_label' => 'Section Heading',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => 'Operating with full legal authorization under the Government of the People\'s Republic of Bangladesh, accredited by international labor platforms and diplomatic missions.',
                'description_label' => 'Intro Description',
                'image' => null,
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '105',
                'theme_id' => '1',
                'page_name' => 'About',
                'link_key' => 'about-licence-card',
                'hints' => 'Ministry Licence',
                'title' => 'Ministry of Expatriates\' Welfare',
                'title_label' => 'Licence / Authority Name',
                'subtitle' => 'Recruiting Licence: <strong>RL-XXXX</strong>',
                'subtitle_label' => 'Licence / Registration Code',
                'button_text' => 'Licensed',
                'button_text_label' => 'Status Badge',
                'button_link' => 'fa-solid fa-building-columns',
                'button_link_label' => 'Icon Class',
                'description' => 'Statutory authorization issued by the Ministry of Expatriates\' Welfare and Overseas Employment to mobilize manpower overseas lawfully.',
                'description_label' => 'Description',
                'image' => 'upload/website-content/award.svg',
                'image_label' => 'Optional Badge / Icon Image',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '106',
                'theme_id' => '1',
                'page_name' => 'About',
                'link_key' => 'about-licence-card',
                'hints' => 'BMET Clearance',
                'title' => 'BMET Emigration Clearance',
                'title_label' => 'Licence / Authority Name',
                'subtitle' => 'Bureau of Manpower, Employment & Training',
                'subtitle_label' => 'Licence / Registration Code',
                'button_text' => 'Govt. Approved',
                'button_text_label' => 'Status Badge',
                'button_link' => 'fa-solid fa-id-card',
                'button_link_label' => 'Icon Class',
                'description' => '100% compliance with biometric fingerprinting, pre-departure briefing (PDO), and issuance of verified BMET Smart Immigration Cards.',
                'description_label' => 'Description',
                'image' => 'upload/website-content/award.svg',
                'image_label' => 'Optional Badge / Icon Image',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '107',
                'theme_id' => '1',
                'page_name' => 'About',
                'link_key' => 'about-licence-card',
                'hints' => 'BAIRA Membership',
                'title' => 'BAIRA Member',
                'title_label' => 'Licence / Authority Name',
                'subtitle' => 'Bangladesh Assoc. of Recruiting Agencies',
                'subtitle_label' => 'Licence / Registration Code',
                'button_text' => 'Active Member',
                'button_text_label' => 'Status Badge',
                'button_link' => 'fa-solid fa-handshake',
                'button_link_label' => 'Icon Class',
                'description' => 'Active registered member strictly adhering to the BAIRA ethical recruitment code, fair migrant practices, and transparent fee policies.',
                'description_label' => 'Description',
                'image' => 'upload/website-content/handshake.svg',
                'image_label' => 'Optional Badge / Icon Image',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '108',
                'theme_id' => '1',
                'page_name' => 'About',
                'link_key' => 'about-licence-card',
                'hints' => 'Wafid & GAMCA',
                'title' => 'Wafid & GAMCA Medical Portal',
                'title_label' => 'Licence / Authority Name',
                'subtitle' => 'Gulf Health Council Medical Registry',
                'subtitle_label' => 'Licence / Registration Code',
                'button_text' => 'GAMCA Certified',
                'button_text_label' => 'Status Badge',
                'button_link' => 'fa-solid fa-heart-pulse',
                'button_link_label' => 'Icon Class',
                'description' => 'Direct medical scheduling with GCC-approved diagnostic centers ensuring only medically fit candidates proceed to overseas visa stamping.',
                'description_label' => 'Description',
                'image' => 'upload/website-content/award.svg',
                'image_label' => 'Optional Badge / Icon Image',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '109',
                'theme_id' => '1',
                'page_name' => 'About',
                'link_key' => 'about-licence-card',
                'hints' => 'Embassy Portals',
                'title' => 'Official Embassy Portals',
                'title_label' => 'Licence / Authority Name',
                'subtitle' => 'Enjaz, MoHRE, FWCMS & IGI',
                'subtitle_label' => 'Licence / Registration Code',
                'button_text' => 'Direct Integration',
                'button_text_label' => 'Status Badge',
                'button_link' => 'fa-solid fa-passport',
                'button_link_label' => 'Icon Class',
                'description' => 'Direct electronic visa stamping integration with Saudi Enjaz, UAE MoHRE, Malaysian Calling Visa (FWCMS), and Romanian Immigration (IGI).',
                'description_label' => 'Description',
                'image' => 'upload/website-content/world.svg',
                'image_label' => 'Optional Badge / Icon Image',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '110',
                'theme_id' => '1',
                'page_name' => 'About',
                'link_key' => 'about-licence-card',
                'hints' => 'ISO 9001:2015',
                'title' => 'ISO 9001:2015 Certified',
                'title_label' => 'Licence / Authority Name',
                'subtitle' => 'Quality Management System',
                'subtitle_label' => 'Licence / Registration Code',
                'button_text' => 'ISO Standard',
                'button_text_label' => 'Status Badge',
                'button_link' => 'fa-solid fa-certificate',
                'button_link_label' => 'Icon Class',
                'description' => 'Audited recruitment workflows, stringent trade test verification, transparent candidate record-keeping, and worker grievance tracking.',
                'description_label' => 'Description',
                'image' => 'upload/website-content/award.svg',
                'image_label' => 'Optional Badge / Icon Image',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== SERVICE PAGE ====================
            [
                'id' => '40',
                'theme_id' => '1',
                'page_name' => 'Service',
                'link_key' => 'service-hero-section',
                'hints' => 'Service Hero Section',
                'title' => 'Our Work Permit Services',
                'title_label' => 'Page Title',
                'subtitle' => 'Verified Overseas Employment Solutions',
                'subtitle_label' => 'Subtitle',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'upload/website-content/63705120240316083855.jpg',
                'image_label' => 'Hero Banner',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '41',
                'theme_id' => '1',
                'page_name' => 'Service',
                'link_key' => 'Service-immigration-section',
                'hints' => 'Service Overview Section',
                'title' => 'OVERSEAS RECRUITMENT & WORK PERMIT SOLUTIONS',
                'title_label' => 'Tagline',
                'subtitle' => 'End-to-End Deployment From',
                'subtitle_label' => 'Subtitle One',
                'button_text' => 'Licensed Manpower Specialists',
                'button_text_label' => 'Subtitle Two',
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p class="guid_p">We provide complete overseas employment and work permit mobilization for Saudi Arabia, UAE, Maldives, Malaysia, and Romania under verified corporate employer quotas.</p>
<div class="accurate_guidance">
    <i class="fa-solid fa-passport"></i>
    <div class="guidance_cont">
        <h3>100% Legal Work Permits</h3>
        <p>All job orders and employment contracts undergo verification through official government immigration portals.</p>
    </div>
</div>
<div class="accurate_guidance">
    <i class="fa-solid fa-plane-departure"></i>
    <div class="guidance_cont">
        <h3>Complete Emigration Deployment</h3>
        <p>From bio-medical fitness screening to embassy visa stamping, BMET Smart Card, and airport flight support.</p>
    </div>
</div>',
                'description_label' => 'Service Features',
                'image' => 'upload/website-content/40942120240316085307.png',
                'image_label' => 'Featured Image',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '42',
                'theme_id' => '1',
                'page_name' => 'Service',
                'link_key' => 'service-tourists-section',
                'hints' => 'Service Country Selector',
                'title' => 'Target Work Permit Destinations',
                'title_label' => 'Section Heading',
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p>Select from our 5 verified employment destinations offering authentic employer quotas, high earning potential, and comprehensive statutory labor protections.</p>',
                'description_label' => 'Description',
                'image' => null,
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== CONTACT PAGE ====================
            [
                'id' => '43',
                'theme_id' => '1',
                'page_name' => 'Contact',
                'link_key' => 'contact-hero-section',
                'hints' => 'Contact Hero Section',
                'title' => 'Contact Us',
                'title_label' => 'Page Title',
                'subtitle' => 'Get in Touch with Our Consular Desk',
                'subtitle_label' => 'Subtitle',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'upload/website-content/94608120240316093652.jpg',
                'image_label' => 'Hero Banner',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '44',
                'theme_id' => '1',
                'page_name' => 'Contact',
                'link_key' => 'contact-company-section',
                'hints' => 'Contact Details',
                'title' => '+880 1700 000 000',
                'title_label' => 'Helpline Phone',
                'subtitle' => 'info@alfahiminternational.com',
                'subtitle_label' => 'Support Email',
                'button_text' => 'Dhaka, Bangladesh',
                'button_text_label' => 'Office Location',
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d116834.00977793444!2d90.34928588523908!3d23.78077774431872!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755b8b087026b81%3A0x8fa563bbdd5904c2!2sDhaka%2C%20Bangladesh!5e0!3m2!1sen!2sbd!4v1709978951525!5m2!1sen!2sbd" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
                'description_label' => 'Google Map Embed',
                'image' => null,
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== BLOG PAGE ====================
            [
                'id' => '45',
                'theme_id' => '1',
                'page_name' => 'Blog',
                'link_key' => 'blog-hero-section',
                'hints' => 'Blog Hero Section',
                'title' => 'Recruitment & Work Permit News',
                'title_label' => 'Page Title',
                'subtitle' => 'Official Notices & Migration Guides',
                'subtitle_label' => 'Subtitle',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'upload/website-content/60340420240317040929.jpg',
                'image_label' => 'Hero Banner',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== TEAM PAGE ====================
            [
                'id' => '46',
                'theme_id' => '1',
                'page_name' => 'Team',
                'link_key' => 'team-hero-section',
                'hints' => 'Team Hero Section',
                'title' => 'Registered Recruitment Experts',
                'title_label' => 'Page Title',
                'subtitle' => 'Dedicated Leadership in Overseas Deployment',
                'subtitle_label' => 'Subtitle',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'upload/website-content/76816420240317041634.jpg',
                'image_label' => 'Hero Banner',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== FAQ PAGE ====================
            [
                'id' => '47',
                'theme_id' => '1',
                'page_name' => 'Faq',
                'link_key' => 'faq-hero-section',
                'hints' => 'Faq Hero Section',
                'title' => 'Frequently Asked Questions',
                'title_label' => 'Page Title',
                'subtitle' => 'Everything You Need to Know About Overseas Work Permits',
                'subtitle_label' => 'Subtitle',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'upload/website-content/36463820240317050425.jpg',
                'image_label' => 'Hero Banner',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '48',
                'theme_id' => '1',
                'page_name' => 'Faq',
                'link_key' => 'faq-accordion-top',
                'hints' => 'Faq Accordion Top',
                'title' => 'WORK PERMIT CLARIFICATIONS',
                'title_label' => 'Tagline',
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<h2>Got Questions About<strong>Work Permit Visas?</strong></h2>',
                'description_label' => 'Header HTML',
                'image' => null,
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '49',
                'theme_id' => '1',
                'page_name' => 'Faq',
                'link_key' => 'faq-accordion',
                'hints' => 'Faq Accordion 1',
                'title' => 'What is the processing timeline for an overseas Work Permit Visa?',
                'title_label' => 'Question',
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p>Processing timelines vary strictly according to the destination country\'s immigration protocols. Middle Eastern destinations like Saudi Arabia and UAE take approximately 3 to 6 weeks from medical clearance to visa stamping. Malaysia Calling Visas (VDR) take 4 to 8 weeks. European work permits (such as Romania Aviz de Munca) require 8 to 12 weeks due to European labor inspectorate quota approvals.</p>',
                'description_label' => 'Answer',
                'image' => null,
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '50',
                'theme_id' => '1',
                'page_name' => 'Faq',
                'link_key' => 'faq-accordion',
                'hints' => 'Faq Accordion 2',
                'title' => 'Is pre-departure medical fitness testing mandatory?',
                'title_label' => 'Question',
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p>Yes, medical fitness clearance is mandatory by law. For Saudi Arabia, testing must be conducted at accredited Wafid (formerly GAMCA) diagnostic centers. Malaysia requires biometric screening at FWCMS-linked clinics. We guide all candidates through authorized diagnostic centers to ensure valid FIT certificates.</p>',
                'description_label' => 'Answer',
                'image' => null,
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '51',
                'theme_id' => '1',
                'page_name' => 'Faq',
                'link_key' => 'faq-accordion',
                'hints' => 'Faq Accordion 3',
                'title' => 'What mandatory benefits are provided by overseas employers?',
                'title_label' => 'Question',
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p>Under our verified corporate job orders, overseas employers are legally obligated to provide company-furnished accommodation, statutory medical insurance, overtime pay (minimum 1.25x – 1.5x regular wage), annual paid vacation, and return flight tickets upon contract completion.</p>',
                'description_label' => 'Answer',
                'image' => null,
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '52',
                'theme_id' => '1',
                'page_name' => 'Faq',
                'link_key' => 'faq-accordion',
                'hints' => 'Faq Accordion 4',
                'title' => 'Do you provide BMET Smart Card emigration clearance?',
                'title_label' => 'Question',
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p>Yes, absolutely. AL FAHIM INTERNATIONAL is a government-approved recruiting agency (RL-XXXX). Every worker deployed through our agency undergoes government biometric fingerprinting, pre-departure orientation, and receives an authentic BMET Smart Card ensuring 100% legal departure and state insurance coverage.</p>',
                'description_label' => 'Answer',
                'image' => null,
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '53',
                'theme_id' => '1',
                'page_name' => 'Faq',
                'link_key' => 'faq-accordion',
                'hints' => 'Faq Accordion 5',
                'title' => 'How can candidates verify the authenticity of their work permit?',
                'title_label' => 'Question',
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p>All work permits can be verified directly on destination government portals: Saudi Qiwa/Muqeem, UAE MoHRE & ICP, Maldives Xpat Online, Malaysia Immigration (JIM/FWCMS), and Romanian General Inspectorate for Immigration (IGI). We provide electronic reference numbers to every applicant.</p>',
                'description_label' => 'Answer',
                'image' => null,
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '54',
                'theme_id' => '1',
                'page_name' => 'Faq',
                'link_key' => 'faq-accordion',
                'hints' => 'Faq Accordion 6',
                'title' => 'What documents are required to apply for an overseas work permit?',
                'title_label' => 'Question',
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p>Key documents include: 1) Original passport valid for at least 12 months; 2) Recent passport-size photographs against a pure white background; 3) Police Clearance Certificate (PCC) attested by the Ministry of Foreign Affairs; 4) Trade certificates or professional diplomas (for technical categories); 5) Authorized bio-medical fitness report.</p>',
                'description_label' => 'Answer',
                'image' => null,
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '55',
                'theme_id' => '1',
                'page_name' => 'Faq',
                'link_key' => 'faq-accordion',
                'hints' => 'Faq Accordion 7',
                'title' => 'Can fresh workers apply, or is prior overseas experience mandatory?',
                'title_label' => 'Question',
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p>Both experienced candidates and fresh job seekers can apply. Technical trades (welding, electrical, plumbing, heavy machinery, culinary) require practical trade testing. General manufacturing, construction, and packing vacancies welcome fresh candidates with pre-departure orientation provided.</p>',
                'description_label' => 'Answer',
                'image' => null,
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '56',
                'theme_id' => '1',
                'page_name' => 'Faq',
                'link_key' => 'faq-accordion',
                'hints' => 'Faq Accordion 8',
                'title' => 'Which countries are currently recruiting through AL FAHIM INTERNATIONAL?',
                'title_label' => 'Question',
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p>We are actively deploying candidates for five premier destination countries: Saudi Arabia, United Arab Emirates (Dubai & Abu Dhabi), Republic of Maldives, Malaysia, and Romania (European Union). All vacancies represent authenticated corporate job quotas.</p>',
                'description_label' => 'Answer',
                'image' => null,
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== TERMS & PRIVACY ====================
            [
                'id' => '63',
                'theme_id' => '1',
                'page_name' => 'Terms of use',
                'link_key' => 'terms-hero-section',
                'hints' => 'Terms Hero Section',
                'title' => 'Terms & Statutory Recruitment Conditions',
                'title_label' => 'Page Title',
                'subtitle' => 'Legal Framework for Overseas Employment Processing',
                'subtitle_label' => 'Subtitle',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'upload/website-content/27021220240325050005.jpg',
                'image_label' => 'Hero Banner',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '64',
                'theme_id' => '1',
                'page_name' => 'Terms of use',
                'link_key' => 'terms-content-section',
                'hints' => 'Terms Section 1',
                'title' => 'Statutory Compliance & Licensing',
                'title_label' => 'Section Title',
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p>AL FAHIM INTERNATIONAL operates strictly under Recruiting License No. RL-XXXX issued by the Ministry of Expatriates\' Welfare and Overseas Employment, Government of Bangladesh. All candidate applications and visa mobilizations are governed by bilateral labor agreements, BMET emigration regulations, and the statutory labor laws of host countries.</p>',
                'description_label' => 'Terms Body',
                'image' => null,
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '65',
                'theme_id' => '1',
                'page_name' => 'Terms of use',
                'link_key' => 'terms-content-section',
                'hints' => 'Terms Section 2',
                'title' => 'Work Permit & Contract Authentication',
                'title_label' => 'Section Title',
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p>All foreign employment offers, salaries, overtime calculations, and worker amenities must be formally declared in the electronic contract approved by the destination government labor authority prior to flight departure. Any unauthorized contract alteration by employers is strictly handled under consular arbitration.</p>',
                'description_label' => 'Terms Body',
                'image' => null,
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '70',
                'theme_id' => '1',
                'page_name' => 'Privacy Policy',
                'link_key' => 'privacy-hero-section',
                'hints' => 'Privacy Hero Section',
                'title' => 'Candidate Data Privacy & Protection Policy',
                'title_label' => 'Page Title',
                'subtitle' => 'Confidentiality of Passports, Medical & Biometric Data',
                'subtitle_label' => 'Subtitle',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'upload/website-content/13607520240325051412.jpg',
                'image_label' => 'Hero Banner',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '71',
                'theme_id' => '1',
                'page_name' => 'Privacy Policy',
                'link_key' => 'privacy-content-section',
                'hints' => 'Privacy Section 1',
                'title' => 'Candidate Document Protection',
                'title_label' => 'Section Title',
                'subtitle' => null,
                'subtitle_label' => null,
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => '<p>Candidate personal records, international passports, academic credentials, and bio-medical diagnostic reports are managed with utmost confidentiality. Documents are only transmitted to authorized consular offices, foreign embassies, BMET verification channels, and certified sponsoring employers.</p>',
                'description_label' => 'Privacy Body',
                'image' => null,
                'image_label' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '77',
                'theme_id' => '1',
                'page_name' => 'Cookie Policy',
                'link_key' => 'cookie-hero-section',
                'hints' => 'Cookie Hero Section',
                'title' => 'Portal Security & Cookie Policy',
                'title_label' => 'Page Title',
                'subtitle' => 'Secure Candidate Portal Navigation',
                'subtitle_label' => 'Subtitle',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'upload/website-content/87310720240325052335.jpg',
                'image_label' => 'Hero Banner',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '84',
                'theme_id' => '1',
                'page_name' => 'Help Center',
                'link_key' => 'help-hero-section',
                'hints' => 'Help Hero Section',
                'title' => 'Need Assistance with Overseas Work Permits? We Are Here to Guide You!',
                'title_label' => 'Page Title',
                'subtitle' => 'Consular Guidance, Medical Slips, and BMET Inquiries',
                'subtitle_label' => 'Subtitle',
                'button_text' => null,
                'button_text_label' => null,
                'button_link' => null,
                'button_link_label' => null,
                'description' => null,
                'description_label' => null,
                'image' => 'upload/website-content/92805520240325061925.jpg',
                'image_label' => 'Hero Banner',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($website_contents as $content) {
            WebsiteContent::updateOrCreate(
                ['id' => $content['id']],
                $content
            );
        }
    }
}
